### ISSUE TITLE
希望收取能量功能与送水功能分开

### ISSUE THREAD

**Issue by biily24** [constanline/XQuickEnergy#11]
希望收取功能与送水功能分开，再不勾选收取能量按钮的时候，送水功能可以正常工作，bate9版本的刷步数貌似不是作用

**Comment by wy41388** [comment]
对的  这个也很重要

**Comment by constanline** [comment]
会在今日将收取与送水分开，步数不生效可能因为启动太早了，beta10版本已经调整为8点后同步步数。

**Comment by biily24** [comment]
> 

谢谢大佬
