### ISSUE TITLE
怀疑芝麻粒和水晶通知栏存在冲突

### ISSUE THREAD

**Issue by TikTokJTT** [constanline/XQuickEnergy#110]
LSPosed
支付宝版本10.3.80 .8800
芝麻粒版本V1.0.18
水晶版本1.55r
MIUI13
安卓12

请看视频:https://wwjp.lanzoul.com/isfRU14x7alc

**Comment by pctit** [comment]
这个好像在新版本里已经修复了

**Comment by TikTokJTT** [comment]
> 这个好像在新版本里已经修复了

Are you sure?

**Comment by TikTokJTT** [comment]
更新1.0.18fix1后问题已解决
