### ISSUE TITLE
商家服务-商家积分页面无法打开

### ISSUE THREAD

**Issue by RadiumLHY** [constanline/XQuickEnergy#115]
如题，换台手机就能正常进入![IMG_20230809_204923.jpg](https://github.com/constanline/XQuickEnergy/assets/36945234/25af6ea3-a89a-4573-9bc4-277f94a65fca)

**Comment by WeyLee89** [comment]
这不是芝麻粒的问题，是手机的问题吧，你试试清理支付宝缓存看一下

**Comment by RadiumLHY** [comment]
> 这不是芝麻粒的问题，是手机的问题吧，你试试清理支付宝缓存看一下

清除缓存没有用，不会要清除全部数据吧

**Comment by constanline** [comment]
与本项目无关。
