### ISSUE TITLE
庄园游戏自定义时间

### ISSUE THREAD

**Issue by HuiNIMA** [constanline/XQuickEnergy#116]
建议增加庄园游戏自定义时间功能，饲料满的情况下零点一过就改全是空宝箱

主页右上角设置与右下角设置功能部分重合，建议将导入导出统计和隐藏图标选项并入设置中的其他选项卡里
![IMG_20230810_011248](https://github.com/constanline/XQuickEnergy/assets/33143156/0d76b693-db84-49d9-bffc-e33fb18e46b5)

**Comment by TikTokJTT** [comment]
+1

**Comment by constanline** [comment]
已添加
