### ISSUE TITLE
保活

### ISSUE THREAD

**Issue by serein061** [constanline/XQuickEnergy#117]
不知道这几个版本保活为什么不如1.10，找不到日志的位置，

**Comment by serein061** [comment]
7点实验功能，开了也是7点20左右才启动
晚上0点基本上都是过几分钟或者20几分钟才启动

**Comment by serein061** [comment]
这是日志

**Comment by serein061** [comment]
https://share.weiyun.com/nMAnBfV1
日志链接

**Comment by constanline** [comment]
保活相比1.10只多了一个设置项，请自行调节尝试。可建议使用水晶或者商家提醒保活。7点启动只在服务未被关闭的时候生效，你这每小时启动应该是其他程序在作用。

**Comment by zhangguanzhang** [comment]
> 保活相比1.10只多了一个设置项，请自行调节尝试。可建议使用水晶或者商家提醒保活。7点启动只在服务未被关闭的时候生效，你这每小时启动应该是其他程序在作用。

老大，这个商家提醒在哪，我谷歌和支付宝里搜索都没找到🤔

**Comment by constanline** [comment]
> 老大，这个商家提醒在哪，我谷歌和支付宝里搜索都没找到🤔

zfb搜索“收钱到账语音提醒”。开启之后可以直接杀掉进程

**Comment by Liujishou** [comment]
还有听书 这个也能后台一直挂着 缺点需要关掉音量

**Comment by Narutojoy** [comment]
> > 老大，这个商家提醒在哪，我谷歌和支付宝里搜索都没找到🤔
> 
> zfb搜索“收钱到账语音提醒”。开启之后可以直接杀掉进程

开启之后还是不佳😂还有没有方法呀

**Comment by cwj851** [comment]
> > > 老大，这个商家提醒在哪，我谷歌和支付宝里搜索都没找到🤔
> > 
> > 
> > zfb搜索“收钱到账语音提醒”。开启之后可以直接杀掉进程
> 
> 开启之后还是不佳😂还有没有方法呀

可以考虑换个杀后台不这么严重的手机😂

**Comment by Narutojoy** [comment]
> > > > 老大，这个商家提醒在哪，我谷歌和支付宝里搜索都没找到🤔
> > > 
> > > 
> > > zfb搜索“收钱到账语音提醒”。开启之后可以直接杀掉进程
> > 
> > 
> > 开启之后还是不佳😂还有没有方法呀
> 
> 可以考虑换个杀后台不这么严重的手机😂

应该不是手机的问题，我是谷歌pixel 6 pro原生安卓系统，后台保留能力很强，基本不会杀任何后台😂

**Comment by constanline** [comment]
#88
