### ISSUE TITLE
可以说一下这些接口是什么方式抓取的吗?我也是写JAVA的,想把代码拉下来自己改着玩一下

### ISSUE THREAD

**Issue by laogao001** [constanline/XQuickEnergy#118]

**Comment by berebrn** [comment]
https://www.52pojie.cn/thread-794312-1-1.html
所有基础原于四哥

**Comment by constanline** [comment]
ddms，或者借助hook。ddms的话就参考二楼的链接，借助hook的可以通过程序的RpcUtil来了解。

**Comment by acooler15** [comment]
ddms不支持android13、android14么？
