### ISSUE TITLE
希望能先优化一下shell启动

### ISSUE THREAD

**Issue by vestige229** [constanline/XQuickEnergy#12]
xposed edge shell命令启动的支付宝虽然能调起插件，但是不能收取能量 1.0.0-9

**Comment by constanline** [comment]
shell命令看下

**Comment by vestige229** [comment]
am start-foreground-service com.eg.android.AlipayGphone/com.alipay.android.launcher.service.LauncherService

**Comment by constanline** [comment]
目前不是注入到com.alipay.android.launcher.service.LauncherService服务，所以重启这个服务没用。

**Comment by P3R5T7U9** [comment]
> am start-foreground-service com.eg.android.AlipayGphone/com.alipay.android.launcher.service.LauncherService

时隔四天，抱歉再打扰了；

近两天才了解到这个新兴的蚂蚁森林收能量的xp模块，之前也用这条shell 命令在“爱玩机工具箱”里运行，想着启动zfb调用模块来收能量，但根本没动静，介不立马来官方仓库的Issue区想着反馈下这个问题，结果四天前已经有层主你反馈过了。。。

看到“constanline”大佬回复到货模块并不是注入到常用的service里，那不知层主你之后找到适用于此模块且可以收能量的shell命令么？？如果已摸索出来的话，麻烦分享下呗，极其想用shell命令来调用此模块

**Comment by P3R5T7U9** [comment]
> 目前不是注入到com.alipay.android.launcher.service.LauncherService服务，所以重启这个服务没用。

抱歉打扰“constanline”大了，挖个坟😜

我是近两天才知道“芝麻粒”这个xp模块，最初也是用此issue中层主发的shell命令来启动zfb调用模块(小声：因为我在用这个模块之前，其它一些收能量的模块用相同的shell命令都可以调起且可以收能量)，一看根本没效果，本想开个issue反馈下，但刚看到四天前已有层主反馈过了，随后见“constanline”大你回复这个模块不是注入到“com.alipay.android.launcher.service.LauncherService"这个最常用的service里。。。

那麻烦“constanline”大再回复甩下调用zfb且可以收能量的“全新”shell命令呗😖 之前翻了下此模块的源码，很多地方由于没注释看⑧懂，一直没找到此模块注入是哪个新servcie😭
(小声：由于我是重度的shell爱好者，弱弱求“constanline”大满足下我这个“特殊癖好”惹)

**Comment by vestige229** [comment]
am start
com.eg.android.AlipayGphone/com.alipay.mobile.framework.service.common.SchemeStartActivity

Mayuu酱重症患者 ***@***.***> 于 2023年7月22日周六 17:18写道：
