### ISSUE TITLE
建议 增加改步数及运动板块的相关功能

### ISSUE THREAD

**Issue by Lincope** [constanline/XQuickEnergy#125]
例如自动走路线 自动捐运动币等等🙏

**Comment by TikTokJTT** [comment]
> 例如自动走路线 自动捐运动币等等🙏

你有用过芝麻粒吗？

**Comment by constanline** [comment]
这个功能由@cwj851提供，已经上线好几天了。

**Comment by Lincope** [comment]
可 但是并不会修改步数哇 ，每天的步数还是我自己原本的步数

**Comment by Lincope** [comment]
> 支付宝要允许获取身体数据的权限，芝麻粒才改得了步数

![S30812-13111261.jpg](https://github.com/constanline/XQuickEnergy/assets/81073939/71edf48c-e31f-4c3e-80a9-ac9031118341)

请问这里面哪个是呀？魅族16th Android 8.1.0

**Comment by Lincope** [comment]
> 安卓8不清楚，你可以进支付宝运动看看有没有权限

应该是有的 水晶正常修改 芝麻粒不行
