### ISSUE TITLE
还是会继续使用的，我观察了不是第头一回了

### ISSUE THREAD

**Issue by chicmr** [constanline/XQuickEnergy#126]
还是会继续使用的，我观察了不是第头一回了
在发现芝麻粒使用双击没收能量后手动去收试试，结果森林提示操作异常。
![Uploading Screenshot_20230811-142746__02__01.jpg…]()

不知道图片上传成功没，贴了个图床：
https://img1.imgtp.com/2023/08/11/OLLeRXPq.jpg

_Originally posted by @chicmr in https://github.com/constanline/XQuickEnergy/issues/124#issuecomment-1674271863_

**Comment by constanline** [comment]
请不要重复提交
