### ISSUE TITLE
虽然后台还在运行，可是不能收能量

### ISSUE THREAD

**Issue by 12nabjuxb** [constanline/XQuickEnergy#127]
为啥我老是用着用着软件就会出现虽然后台还在运行，可是不能收能量，且三个日志都打不开的情况。
![Screenshot_20230811_152235_com huawei android lau](https://github.com/constanline/XQuickEnergy/assets/141997327/b2677bb4-8afe-403f-90ec-39d14353dc1c)
就像这样虽然看着还在运行可是好像已经停止工作了，并且打不开日志。

**Comment by xiaoqi2020** [comment]
我也有这个情况，我没 root，用的补丁的方式运行的

**Comment by constanline** [comment]
问题请描述清楚，找到一个可能的原因，今日更新后看下效果

**Comment by xiaoqi2020** [comment]
> 问题请描述清楚，找到一个可能的原因，今日更新后看下效果

我也是一样的问题，后台挂一会后，状态栏要么显示正在检测，要么显示登录超时，我尝试过晚上打开支付后锁屏，到第二天早上起来，状态栏显示貌似正常，但是实际上也没有工作，插件里面的各项日志也打不开，只有强制停止支付宝后重新打开，才恢复正常

**Comment by constanline** [comment]
更新后效果如何

**Comment by constanline** [comment]
后台问题发日志看下，闪退的问题要发闪退日志。另外日志打不开不是挂久了打不开吧，打不开应该是权限问题。

**Comment by xiaoqi2020** [comment]
> 后台问题发日志看下，闪退的问题要发闪退日志。另外日志打不开不是挂久了打不开吧，打不开应该是权限问题。
请教怎么提取日志给你? 插件给了读写权限的，打不开日志真的是挂久了后打不开的。

**Comment by TikTokJTT** [comment]
> 后台问题发日志看下，闪退的问题要发闪退日志。另外日志打不开不是挂久了打不开吧，打不开应该是权限问题。

作者大大，要不通知栏上面也加一下版本号吧，这样有些人提问的时候也方便解答一些。

**Comment by 12nabjuxb** [comment]
我用了水晶1.5.5配合使用，现在就没有存在过这个问题了。不过更新到最新版了会存在多次兑换限时能量卡的情况
