### ISSUE TITLE
捐步无效

### ISSUE THREAD

**Issue by xiaoqi2020** [constanline/XQuickEnergy#128]
捐运动币可以，捐步兑换公积金无效

**Comment by LazyImmortal** [comment]
怎么证明你的配置没有问题？同步步数大于最小捐步步数了吗？最晚捐步时间过了吗？

**Comment by Liujishou** [comment]
> 捐运动币可以，捐步兑换公积金无效

可以的，估计是你设置问题，默认改步数是早6点，所以你的最晚捐步要设置6点之后，最小捐步 要设置比你设置同步步数要小

**Comment by constanline** [comment]
楼上的问题也是我想问的，如果无反馈就关闭了
