### ISSUE TITLE
大雕能否教下如何抓取指令，需要自己新增功能

### ISSUE THREAD

**Issue by WYC-2020** [constanline/XQuickEnergy#129]
目前这边自己写了一个模块，hook了rpcCall 这个接口，但是打印出来的东西完全不对，一直是alipay.mappconfig.appContainerCheck这一个东西，hook 是完全正确的，因为如果开启芝麻粒，然后我这个hook也开启的话 是能抓取到芝麻粒的所有请求参数的，但是如果用原版支付宝+我这个hook 就抓不到这些，按理应该也能抓到才对，请大佬指点一下
支付宝版本是：10.3.86
抓取的日志如下文件：
[debug.log](https://github.com/constanline/XQuickEnergy/files/12320273/debug.log)

**Comment by cwj851** [comment]
#118 看这个前面的issues

**Comment by WYC-2020** [comment]
新版已经不是这个rpc这里了，已解决

**Comment by acooler15** [comment]
> 新版已经不是这个rpc这里了，已解决

大佬如何抓取的？
