### ISSUE TITLE
芝麻粒会一直挂在后台运行，但会过段时间不收能量，强制关闭支付宝，再打开支付宝时才会继续收能量

### ISSUE THREAD

**Issue by dsjun007** [constanline/XQuickEnergy#130]
如题，芝麻粒会一直挂在后台运行，但会过段时间不收能量，早上7点到7点半也会有，强制关闭支付宝，再打开支付宝时才会继续收能量，miui14，root，lsp，设置检测间隔时间为2分钟，其余默认。谢谢你！
![IMG_20230811_174836](https://github.com/constanline/XQuickEnergy/assets/139686773/033dfc94-920b-43e2-a461-5a0fa839914b)

**Comment by xiaoqi2020** [comment]
我也有这个问题

**Comment by 12nabjuxb** [comment]
我也是，我也是。上边明明显示还在运行啊，可是就是不收能量了。

**Comment by luzilong520** [comment]
大家都是这个问题

**Comment by OldCoding** [comment]
同样的问题，通知栏显示正常，但已收能量显示为0，啥都不工作，必须要重新打开

**Comment by Narutojoy** [comment]
我也是！

**Comment by ainiyong86** [comment]
原来大家和我一样的问题😁

**Comment by xiaoqi2020** [comment]
最新进展，我晚上睡觉的时候，把支付宝打开后锁屏，到第二天早上起来打开看，刷步数成功了，收取能量没反应

**Comment by Xiepoder** [comment]
我也有这个问题

**Comment by constanline** [comment]
#127 不要重复提问
