### ISSUE TITLE
后台不工作

### ISSUE THREAD

**Issue by xiaoqi2020** [constanline/XQuickEnergy#133]
后台挂一会儿后，要么显示登录超时，要么显示开始检测能量！求大佬修复！
荣耀 70
非 root lspatch 内嵌模块运行！

**Comment by constanline** [comment]
登录超时不是bug，自行调整保活设置尝试合适的方式。后台挂一会，显示开始检测能量，这情况还有吗

**Comment by constanline** [comment]
#127

**Comment by constanline** [comment]
现在情况如何，无新反馈的话就关掉了

**Comment by xiaoqi2020** [comment]
> 现在情况如何，无新反馈的话就关掉了

谢谢大佬百忙之中关注修复 bug，我在另一个反馈里面回复了
![Screenshot_20230815_064221](https://github.com/constanline/XQuickEnergy/assets/50669177/f42784ca-ceb4-40f4-a4e5-fda414039b7f)

截图是 1.0.21 的时候截的，1.1.1 也是一样的
我更新 1.1.1 后，状态栏虽然没有再报错了，但是后台不稳定，偶尔会偷取一个人的能量，自己打开支付宝点找能量还是可以找到的，其他的也没有执行，停止支付宝后重新打开才会执行，而且挂久了以后，日志打不开了，应该是插件后台崩了。
另外我是用的 lspatch 补丁的方式运行的，所以每次更新插件都要把支付宝卸载了重新补丁，从 1.0 开始，打开支付宝会一直闪退，1.1.1 更严重了，一直点，一直点，直到打开为止，赶紧登录账号，然后就不会闪退了！

**Comment by constanline** [comment]
> 请教怎么提取日志给你? 插件给了读写权限的，打不开日志真的是挂久了后打不开的。

日志在你截图的目录下。我猜不需要挂久了，一开始就打不开。

**Comment by xiaoqi2020** [comment]
> > 请教怎么提取日志给你? 插件给了读写权限的，打不开日志真的是挂久了后打不开的。
> 
> 日志在你截图的目录下。我猜不需要挂久了，一开始就打不开。
[runtime.log](https://github.com/constanline/XQuickEnergy/files/12373988/runtime.log)

**Comment by xiaoqi2020** [comment]
> > 请教怎么提取日志给你? 插件给了读写权限的，打不开日志真的是挂久了后打不开的。
> 
> 日志在你截图的目录下。我猜不需要挂久了，一开始就打不开。

[simple.log](https://github.com/constanline/XQuickEnergy/files/12373999/simple.log)

**Comment by constanline** [comment]
> [runtime.log](https://github.com/constanline/XQuickEnergy/files/12373988/runtime.log)

看了下日志，登录超时，开启“到账语音提醒”试试看

**Comment by xiaoqi2020** [comment]
> > [runtime.log](https://github.com/constanline/XQuickEnergy/files/12373988/runtime.log)
> 
> 看了下日志，登录超时，开启“到账语音提醒”试试看

现在没有提示登录超时了！
以下是早上更新 1.1.2 版本后打开支付宝的运行截图，可以看到就打开那几分钟工作过，然后就一直没有运行日志了！强制停止支付宝后才会继续工作！

![Screenshot_20230818_113339](https://github.com/constanline/XQuickEnergy/assets/50669177/ccd25d9e-36d8-4fd3-a475-25ce55b31d5c)
[simple.log](https://github.com/constanline/XQuickEnergy/files/12375068/simple.log)
[other.log](https://github.com/constanline/XQuickEnergy/files/12375069/other.log)
[farm.log](https://github.com/constanline/XQuickEnergy/files/12375071/farm.log)

**Comment by xiaoqi2020** [comment]
> > [runtime.log](https://github.com/constanline/XQuickEnergy/files/12373988/runtime.log)
> 
> 看了下日志，登录超时，开启“到账语音提醒”试试看

作者大大，按你的说法把收款语音打开后我发现支付宝后台挂机一会儿后就自动退出了，状态栏也不显示语音的横条，没用插件的时候是正常挂着的，之前用水晶 1.5.0 的时候也是正常的，但是水晶 1.5.5 很多人都蹦后台，不知道什么原因，辛苦排查一下

**Comment by ConjuringLee** [comment]
+1，目前遇到一样的情形。已经将支付宝电池管理选项设置为无限制，且锁住后台，但工作一段时间后（几分钟），手动去收能量发现还有漏网之鱼，此时芝麻粒已是停止工作的状态。

**Comment by constanline** [comment]
用最新版试下
