### ISSUE TITLE
请问：气泡纵向偏移 这个怎么设置？

### ISSUE THREAD

**Issue by Liujishou** [constanline/XQuickEnergy#142]
现在气泡在中间位置，想要回到底部原来的位置是要怎么填写呢？

**Comment by dsjun007** [comment]
我设置的5000，直接到最上面了

**Comment by zhangguanzhang** [comment]
> 我设置的5000，直接到最上面了

你们说的这个在哪设置，我咋没看到

**Comment by Liujishou** [comment]
> 我设置的5000，直接到最上面了

这么说 放底下就负数？

**Comment by WeyLee89** [comment]
我填850，差不多回到原来显示的位置

**Comment by Liujishou** [comment]
ok 懂了！！close！！

**Comment by constanline** [comment]
填正数向下偏移，填负数向上偏移，注意都不要太大，具体填多少要看手机的像素
