### ISSUE TITLE
森林记录日志每条收取记录的年月日可以去除吗，使用了双击卡，太多都会显示两行，日志是每天一生成，前面的年月日就不需要了

### ISSUE THREAD

**Issue by dsjun007** [constanline/XQuickEnergy#143]
如题，森林记录日志每条收取记录的年月日可以去除吗，使用了双击卡，太多都会显示两行，日志是每天一生成，前面的年月日就不需要了
气泡可以换位置了，真是太贴心了，感谢作者。
另外有个小小的建议，森林记录日志和气泡提示里可以把“偷取能量”改为“收取能量”不，虽然事实就是在偷能量🙈
感谢作者👍👍
![IMG_20230812_095718](https://github.com/constanline/XQuickEnergy/assets/139686773/54fa54ec-0e8e-4e15-812f-cb3c8c300c2c)

**Comment by Liujishou** [comment]
自己 可以改util-log.java里
getFormatDateTime替换为getFormatTime

**Comment by Zhangfanyu1222** [comment]
接上一条，有目录了，自己用编辑器查找替换一下不难吧？
时间在XQuickEnergy\app\src\main\java\pansong291\xposed\quickenergy\util\log.java
能量在XQuickEnergy\app\src\main\java\pansong291\xposed\quickenergy\AntForest.java。

**Comment by TikTokJTT** [comment]
> apk

赞成！

作者是有家庭有工作的，闲暇之余每天都抽空来更新已经很不容易了，不要逮住一只羊来薅。

**Comment by luzilong520** [comment]
没得时候又在叫，等有了又在叫，人家作者不是只为你服务，有得用就行，不要想着你想怎样就怎样

**Comment by dsjun007** [comment]
> 这些 自己 可以改 时间在log.java getFormatDateTime替换为getFormatTime
> 
> “偷取能量”改为“收取能量”在AntForest.java
> 
> 然后自己打包apk

好的，这个是不是每次更新之后打包都需要自己先修改

**Comment by dsjun007** [comment]
> 接上一条，有目录了，自己用编辑器查找替换一下不难吧？ 时间在XQuickEnergy\app\src\main\java\pansong291\xposed\quickenergy\util\log.java 能量在XQuickEnergy\app\src\main\java\pansong291\xposed\quickenergy\AntForest.java。

好的，又学了新知识

**Comment by dsjun007** [comment]
@Liujishou getFormatDateTime替换为getFormatTime，是把这个文件下所有的都替换吗
我试了只删除yyyy-，打包了支付宝闪退。
谢谢！
![IMG_20230813_105308](https://github.com/constanline/XQuickEnergy/assets/139686773/8be800c1-a75d-4de7-996a-6ed7ac81e5b8)

**Comment by Liujishou** [comment]
> getFormatDateTime

![image](https://github.com/constanline/XQuickEnergy/assets/79367462/906456e6-bfa0-4ded-935b-1837f87f01ef)

**Comment by Liujishou** [comment]
> @LiujishougetFormatDateTime替换为getFormatTime，是把这个文件下所有的都替换吗 我试了只删除yyyy-，预留了支付宝闪退。 谢谢！ ![IMG_20230813_105308](https://user-images.githubusercontent.com/139686773/260277055-8be800c1-a75d-4de7-996a-6ed7ac81e5b8.jpg)

目前就森林才会显示年月日，就改森林日志那里就可以了，其他地方不用改！

**Comment by Zhangfanyu1222** [comment]
1.1.1的新版本中作者已经把“getFormatDateTime”改成“getFormatTime”了，不需要自己修改了。
