### ISSUE TITLE
建议隐藏图标添加二次确认，并且强制5秒后才能确认

### ISSUE THREAD

**Issue by alinnse** [constanline/XQuickEnergy#144]

**Comment by Zhangfanyu1222** [comment]
没啥用

**Comment by alinnse** [comment]
> 没啥用

有用的，不少lspatch用户误点隐藏找不回来

**Comment by TikTokJTT** [comment]
现在还有人点击右上角三个点的按钮？如果这样都被你点到了那你活该。
真是什么鸡毛蒜皮的问题都发，作者的时间就不是时间吗？

**Comment by alinnse** [comment]
> 现在还有人点击右上角三个点的按钮？如果这样都被你点到了那你活该。
> 真是什么鸡毛蒜皮的问题都发，作者的时间就不是时间吗？

只是建议而已，作者不想更会关掉，不用你置气。
另外作者时间宝贵大家都知道不用你提。
还有，你嘴真tm臭

**Comment by TikTokJTT** [comment]
> > 现在还有人点击右上角三个点的按钮？如果这样都被你点到了那你活该。
> > 真是什么鸡毛蒜皮的问题都发，作者的时间就不是时间吗？
> 
> 只是建议而已，作者不想更会关掉，不用你置气。
> 另外作者时间宝贵大家都知道不用你提。
> 还有，你嘴真tm臭

你在玩兰博？？？

**Comment by LazyImmortal** [comment]
> > 没啥用
> 
> 有用的，不少lspatch用户误点隐藏找不回来

那就去LSPatch里通过模块设置进去软件界面，然后把隐藏图标关了。 建议先把LSPatch摸熟了再说。

**Comment by hellbearchg** [comment]
没啥用的建议

**Comment by WeyLee89** [comment]
用lsp内置，误点隐藏，可以直接卸载芝麻粒再重装，不需要另外让作者添加这功能，还不如让作者把精力增加一些实用的功能

**Comment by yucotang** [comment]
确实没啥用

**Comment by constanline** [comment]
> > 没啥用
> 
> 有用的，不少lspatch用户误点隐藏找不回来
LSPatch-管理-模块，可以直接打开模块
