### ISSUE TITLE
关于打包过程遇到的问题

### ISSUE THREAD

**Issue by smdio** [constanline/XQuickEnergy#154]
我fork了项目后，修改了github actions的releases.yml文件，但是创建releases的时候自动运行的github actions还是执行的作者的yml文件，如图。![image](https://github.com/constanline/XQuickEnergy/assets/90607030/35324326-056d-4391-a20a-1b95faea1ac4)

**Comment by TikTokJTT** [comment]
作者的releases.yml你可以禁用，也可以删除覆盖都可以，你可以参考一下我的。

**Comment by smdio** [comment]
好的，谢谢您，我试试看
