### ISSUE TITLE
建议：优化森林活力值任务

### ISSUE THREAD

**Issue by Liujishou** [constanline/XQuickEnergy#157]
目前森林功能全了。经过几天的观察，活力任务会随机出，做了第一轮还会出，特别是将“每天做一件环保小事”打卡，后就会出第二轮的随机任务。（不知是不所有人都这样）
看能不能优化下将“每天做一件环保小事”打卡加上把第二轮的活力任务也给做了。

**Comment by constanline** [comment]
功能已包含
