### ISSUE TITLE
保护古树没作用

### ISSUE THREAD

**Issue by yanxinzi** [constanline/XQuickEnergy#158]
版本：`v1.0.18-fix1`
支付宝：`10.3.86.8000`

点了保护地列表，没有出来保护地，只有搜索  
开启了`保护古树`功能没作用

**Comment by constanline** [comment]
首先请使用新版反馈，另外检查配置文件里是否自行设置过cityCode，设置是否正确

**Comment by yanxinzi** [comment]
> 首先请使用新版反馈，另外检查配置文件里是否自行设置过cityCode，设置是否正确

都不知道还有配置文件这一回事，请问路径在哪呢，我手动设置看是否可行

**Comment by Zhangfanyu1222** [comment]
> > 首先请使用新版反馈，另外检查配置文件里是否自行设置过cityCode，设置是否正确
> 
> 都不知道还有配置文件这一回事，请问路径在哪呢，我手动设置看是否可行

建议先更新最新版 1.0.21 ，配置文件在手机外部存储目录的download/xqe

**Comment by yanxinzi** [comment]
> > > 首先请使用新版反馈，另外检查配置文件里是否自行设置过cityCode，设置是否正确
> > 
> > 
> > 都不知道还有配置文件这一回事，请问路径在哪呢，我手动设置看是否可行
> 
> 建议先更新最新版 1.0.21 ，配置文件在手机外部存储目录的download/xqe

没有看到新版呢，github上最新就是我反馈的那个啊

**Comment by Zhangfanyu1222** [comment]
> > > > 首先请使用新版反馈，另外检查配置文件里是否自行设置过cityCode，设置是否正确
> > > 
> > > 
> > > 都不知道还有配置文件这一回事，请问路径在哪呢，我手动设置看是否可行
> > 
> > 
> > 建议先更新最新版 1.0.21 ，配置文件在手机外部存储目录的download/xqe
> 
> 没有看到新版呢，github上最新就是我反馈的那个啊

最新版需要fork项目自行打包

**Comment by yanxinzi** [comment]
> > > > > 首先请使用新版反馈，另外检查配置文件里是否自行设置过cityCode，设置是否正确
> > > > 
> > > > 
> > > > 都不知道还有配置文件这一回事，请问路径在哪呢，我手动设置看是否可行
> > > 
> > > 
> > > 建议先更新最新版 1.0.21 ，配置文件在手机外部存储目录的download/xqe
> > 
> > 
> > 没有看到新版呢，github上最新就是我反馈的那个啊
> 
> 最新版需要fork项目自行打包

知识盲区，不懂得怎么操作

**Comment by Zhangfanyu1222** [comment]
> > > > > > 首先请使用新版反馈，另外检查配置文件里是否自行设置过cityCode，设置是否正确
> > > > > 
> > > > > 
> > > > > 都不知道还有配置文件这一回事，请问路径在哪呢，我手动设置看是否可行
> > > > 
> > > > 
> > > > 建议先更新最新版 1.0.21 ，配置文件在手机外部存储目录的download/xqe
> > > 
> > > 
> > > 没有看到新版呢，github上最新就是我反馈的那个啊
> > 
> > 
> > 最新版需要fork项目自行打包
> 
> 知识盲区，不懂得怎么操作

可以看看谁的仓库已经打包好了先用着，然后再自己慢慢学

**Comment by constanline** [comment]
download/xqe/cityCode.json文件是否存在

**Comment by yanxinzi** [comment]
> 

没有这个文件呢，已更新到`v1.1.0`

**Comment by Zhangfanyu1222** [comment]
> > 
> 
> 没有这个文件呢，已更新到`v1.1.0`

保护古树的开关打开了吗？

**Comment by constanline** [comment]
> 没有这个文件呢，已更新到`v1.1.0`

那看下日志吧

**Comment by yanxinzi** [comment]
> 保护古树的开关打开了吗？

有打开，而且`古树区域代码列表`也有勾选

你说的看日志是哪个文件呢

**Comment by yanxinzi** [comment]
`download/xqe/cityCode.json` 虽然没有该文件，今天看了森林日志，发现可以正常执行保护古树
