### ISSUE TITLE
建议功能开关默认关闭，有需要自行打开

### ISSUE THREAD

**Issue by wanwan411** [constanline/XQuickEnergy#161]
因为有些功能会消耗能量，打扰好友，什么的

**Comment by cwj851** [comment]
运行插件之前自己修改设置不就好了，会消耗能量的就算开关打开，你不配置列表也不会启用该功能

**Comment by Zhangfanyu1222** [comment]
激活模块之前自己先把开关关了，然后再激活模块就好了

**Comment by constanline** [comment]
除了某些安全、保密性强、后果严重的配置，默认选项一般会采用大多数人最常用的设置。所以不会设为默认关闭
