### ISSUE TITLE
看更新记录增加派遣动物的功能，但是设置里面没看到呢?

### ISSUE THREAD

**Issue by xiaoqi2020** [constanline/XQuickEnergy#167]

**Comment by LazyImmortal** [comment]
是英文的，还没汉化呢。

**Comment by Liujishou** [comment]
fork项目 自行打包

**Comment by xiaoqi2020** [comment]
> fork项目 自行打包

不会打包。

**Comment by xiaoqi2020** [comment]
> 是英文的，还没汉化呢。

好的

**Comment by LazyImmortal** [comment]
> > fork项目 自行打包
> 
> 不会打包。

所以你用的版本不是1.0.21吗？

**Comment by xiaoqi2020** [comment]
> > > fork项目 自行打包
> > 
> > 
> > 不会打包。
> 
> 所以你用的版本不是1.0.21吗？

下载的最新版是 1.0.18 fix1 呀

**Comment by LazyImmortal** [comment]
> > > > fork项目 自行打包
> > > 
> > > 
> > > 不会打包。
> > 
> > 
> > 所以你用的版本不是1.0.21吗？
> 
> 下载的最新版是 1.0.18 fix1 呀

阿这，那你怎么好意思来问的？这个功能是1.0.21新加进来的……

**Comment by Zhangfanyu1222** [comment]
功能在今天最新的1.0.21 版本

**Comment by WenRou-Pan** [comment]
> > > > > fork项目 自行打包
> > > > 
> > > > 
> > > > 不会打包。
> > > 
> > > 
> > > 所以你用的版本不是1.0.21吗？
> > 
> > 
> > 下载的最新版是 1.0.18 fix1 呀
> 
> 阿这，那你怎么好意思来问的？这个功能是1.0.21新加进来的……

别人不知道还不能问，给爷看笑了

**Comment by xiaoqi2020** [comment]
> 
![image](https://github.com/constanline/XQuickEnergy/assets/50669177/a56e6e1a-4a6b-4b22-9bc7-a76260d77a4f)

我不知道你是在哪里下载的 1.0.21
我这边看到最新版是 1.0.18

**Comment by xiaoqi2020** [comment]
> 功能在今天最新的1.0.21 版本

为啥我看到的最新版是 1.0.18？
![image](https://github.com/constanline/XQuickEnergy/assets/50669177/7e22f07f-628f-43f7-8671-314a45d97e70)

**Comment by Zhangfanyu1222** [comment]
> > 功能在今天最新的1.0.21 版本
> 
> 为啥我看到的最新版是 1.0.18？ ![image](https://user-images.githubusercontent.com/50669177/260376630-7e22f07f-628f-43f7-8671-314a45d97e70.png)

因为最新版需要自己打包了

**Comment by LazyImmortal** [comment]
> > > > > > fork项目 自行打包
> > > > > 
> > > > > 
> > > > > 不会打包。
> > > > 
> > > > 
> > > > 所以你用的版本不是1.0.21吗？
> > > 
> > > 
> > > 下载的最新版是 1.0.18 fix1 呀
> > 
> > 
> > 阿这，那你怎么好意思来问的？这个功能是1.0.21新加进来的……
> 
> 别人不知道还不能问，给爷看笑了

提问之前不得保证自己是最新版吗？几天前发布的版本怎么可能有今天刚上传的代码内容？你这是什么爷？
