### ISSUE TITLE
大佬上次说的那个重复兑换bug又出来了

### ISSUE THREAD

**Issue by berebrn** [constanline/XQuickEnergy#173]
![Screenshot_2023-08-14-17-26-57-090_pansong291 xposed quickenergy repair](https://github.com/constanline/XQuickEnergy/assets/140738041/70c3b4a7-efc7-44ef-8ad8-38e20d92a55d)
![Screenshot_2023-08-14-17-26-28-539_pansong291 xposed quickenergy repair](https://github.com/constanline/XQuickEnergy/assets/140738041/436ac76e-d7ed-4097-a8fa-67da97cf2833)

**Comment by berebrn** [comment]
[forest.log](https://github.com/constanline/XQuickEnergy/files/12333447/forest.log)

**Comment by Liujishou** [comment]
这个日志文件看不出什么的 要runtime.log，上传前要把里面的个人信息清除一下

**Comment by Liujishou** [comment]
> > 这个日志文件看不出什么的 要运行时.log，上传前要把里面的个人信息清除一下
> 
> runtime.log记录是下午四点的，前面的被清空了

那没办法了，默认30MB就清除数据，或者你去FileUtils.java改下 if (getRuntimeLogFile().length() > 31_457_280) // 30MB

**Comment by berebrn** [comment]
> > > 这个日志文件看不出什么的 要运行时.log，上传前要把里面的个人信息清除一下
> > 
> > 
> > runtime.log记录是下午四点的，前面的被清空了
> 
> 那没办法了，默认30MB就清除数据，或者你去FileUtils.java改下 if (getRuntimeLogFile().length() > 31_457_280) // 30MB

😂不会啊，那要等下次我遇到再上传

**Comment by berebrn** [comment]
> > > > 这个日志文件看不出什么的 要运行时.log，上传前要把里面的个人信息清除一下
> > > 
> > > 
> > > runtime.log记录是下午四点的，前面的被清空了
> > 
> > 
> > 那没办法了，默认30MB就清除数据，或者你去FileUtils.java改下 if (getRuntimeLogFile().length() > 31_457_280) // 30MB
> 
> joy不会啊，那要等下次我遇到再上传

![Screenshot_2023-08-14-20-04-46-017_pansong291 xposed quickenergy repair](https://github.com/constanline/XQuickEnergy/assets/140738041/afe8bef5-7e9b-473e-a882-40f445aa560e)
我又注意到出现重复兑换会自动清空runtime.log数据，能不能单独引导一个异常log，用来分析

**Comment by constanline** [comment]
runtime是满30m清空。异常和报错不一样，异常在发现之后才知道是异常。runtime修改为改名，如果再出现看下备份的日志文件

**Comment by Liujishou** [comment]
> > runtime是满30m清空。异常和报错不一样，异常在发现之后才知道是异常。runtime修改为满30m改名而非删除，如果再出现看下备份的日志文件
> 
> 是按照楼上的大佬说的代码复制过去吗？

你不用改，最新版本已经改为满30MB会备份，如果你还出现问题，到时候找备份文件来看看

**Comment by berebrn** [comment]
> > > runtime是满30m清空。异常和报错不一样，异常在发现之后才知道是异常。runtime修改为满30m改名而非删除，如果再出现看下备份的日志文件
> > 
> > 
> > 是按照楼上的大佬说的代码复制过去吗？
> 
> 你不用改，最新版本已经改为满30MB会备份，如果你还出现问题，到时候找备份文件来看看

多谢大佬指点，辛苦了🤝时候不早了，早点休息，晚安💤

**Comment by constanline** [comment]
是否还存在问题，如果存在问题请把infoChaged文件上传下

**Comment by berebrn** [comment]
> 是否还存在问题，如果存在问题请把infoChaged文件上传下

目前没事，好的，大佬。现在在外面晚上回去再给你图标

**Comment by 12nabjuxb** [comment]
我的也有这个问题呢，本来设置的兑换一个，昨天兑换了两个，今天兑换了，三个。
