### ISSUE TITLE
后台依然不工作

### ISSUE THREAD

**Issue by xiaoqi2020** [constanline/XQuickEnergy#174]
我不问了，各位也别喷了！

**Comment by xiaoqi2020** [comment]
1.0.18 修复版

**Comment by TikTokJTT** [comment]
> 1.0.18 修复版

麻烦你用个V1.0.21再说话

**Comment by Zhangfanyu1222** [comment]
为什么一直抓着1.0.18fix来问问题（捂脸）

**Comment by xiaoqi2020** [comment]
> 为什么一直抓着1.0.18fix来问问题（捂脸）

我下不到 1.0.21，自己又不会打包。。。

**Comment by Zhangfanyu1222** [comment]
> > 为什么一直抓着1.0.18fix来问问题（捂脸）
> 
> 我下不到 1.0.21，自己又不会打包。。。

(⊙o⊙)…好吧，其实楼上老哥和我的仓库里都有打包好的
