### ISSUE TITLE
单个账号多次不同时间签到

### ISSUE THREAD

**Issue by sundongxiao** [constanline/XQuickEnergy#175]
![Screenshot_2023-08-14-20-10-12-832_pansong291 xposed quickenergy repair](https://github.com/constanline/XQuickEnergy/assets/33159212/354248ff-bb64-4493-815d-09d9027be8b9)

**Comment by sundongxiao** [comment]
运行log请查看[其他log](https://stan-d.lanzoul.com/iUGED15dsbwb)

**Comment by sundongxiao** [comment]
[other.log](https://github.com/constanline/XQuickEnergy/files/12334530/other.log)
此为电脑上传文件

**Comment by constanline** [comment]
需要runtime日志，最好有配置文件

**Comment by sundongxiao** [comment]
请查收[runtime.log](https://stan-d.lanzoul.com/iauem15e9oaj)

**Comment by sundongxiao** [comment]
配置文件[config.json](https://stan-d.lanzoul.com/ixBCW15ea43i)

**Comment by sundongxiao** [comment]
> > 请查收[runtime.log](https://stan-d.lanzoul.com/iauem15e9oaj)
> 
> ![image](https://user-images.githubusercontent.com/34029504/260600516-5a0494bc-b6ac-4337-afd7-3e9358d15339.png) 2023-08-14 22:41:39 pansong291.xposed.quickenergy.util.Statistics, 重新格式化 statistics.json 有手动改过statistics吗？

没有进行过手动修改

**Comment by constanline** [comment]
今天会加入statistics变动记录，查看究竟是什么导致部分统计失效。如果更新后还有问题，请提交infoChange日志

**Comment by sundongxiao** [comment]
> 今天会加入statistics变动记录，查看究竟是什么导致部分统计失效。如果更新后还有问题，请提交infoChange日志

好的

**Comment by constanline** [comment]
问题是否再次出现，如果有请上传infoChange日志

**Comment by sundongxiao** [comment]
![微信图片_20230816193303](https://github.com/constanline/XQuickEnergy/assets/33159212/fd1f3367-7b25-418a-bf91-bb6832c09001)
使用最新版芝麻粒1.1.1未发现有此异常。
