### ISSUE TITLE
测试了一下芝麻粒v1版本，不开启收取能量，无法启动芝麻粒插件

### ISSUE THREAD

**Issue by biily24** [constanline/XQuickEnergy#18]
不勾选收取能量，挂完全不启动，连状态栏都不出现，只要勾选了收取能量按钮，就开始工作了，状态栏出现进程，所以在不开启收取能量情况下，插件不工作
使用双击的机制是怎样的，我手动使用双击卡，但是芝麻粒也还是只收取一次

**Comment by constanline** [comment]
通知栏不出现是正常的。如果收能量和农场都不开启，通知栏就不会显示。
插件部分功能不工作出于计次(times参数)原因，下个版本不再使用此参数。
双击机制有两方面。1、7:00-7:25期间，如果双击卡未启用或已失效，则在收能量之前启用它；2、任何时间，如果收取一次能量后可以再次收取，就再收一遍。群里未收到双击卡失效反馈，需要日志进一步确认原因

**Comment by constanline** [comment]
确认双击卡有效，但是两次扫描之间手动使用的双击卡无效。需要验证收能量返回消息是否支持，如果支持会在下个版本调整为任意时间双击卡期间生效。

**Comment by biily24** [comment]
> 
1，我说详细一点，我不勾选收取能量，不勾选农庄，只勾选能量雨和送水，这样是不工作的，但是我勾选了收取能量后，就工作了，能量雨和送水都可以
2，我是凌晨0点使用双击卡，芝麻粒无法自动摸水两次，如果按照您的下个版本的任意时间双击机制计划，是不是把所有球都摸一次后，再检测后发现还有球，在执行再摸水工作，这样的话，双击卡可能就失效了
