### ISSUE TITLE
感觉可以在每个操作之间加一个随机等待时间。

### ISSUE THREAD

**Issue by sbtang17** [constanline/XQuickEnergy#180]
如题，这样的话估计不会经常出现请求错误和登录超时啥的。个人建议哈，比较麻烦的话就算了，现在这样已经很好了，感谢作者们的无私付出！

**Comment by constanline** [comment]
登录超时是zfb机制，跟操作无关。异常目前只出现在森林，森林的操作是可以设置间隔的。
