### ISSUE TITLE
有没有办法优化这种图标‘□’或许取消图标（不重要的个人想法）

### ISSUE THREAD

**Issue by berebrn** [constanline/XQuickEnergy#188]
![IMG_20230816_002253](https://github.com/constanline/XQuickEnergy/assets/140738041/585c6653-48c6-41e2-a489-bafd0db022d7)
![IMG_20230816_002631](https://github.com/constanline/XQuickEnergy/assets/140738041/f6bbaf71-4467-4556-a0ac-374de81bf27b)
![IMG_20230816_002550](https://github.com/constanline/XQuickEnergy/assets/140738041/4663fe94-a6f0-4707-856e-d877f0280289)

**Comment by Liujishou** [comment]
![image](https://github.com/constanline/XQuickEnergy/assets/79367462/94219208-e412-4143-af78-ecd6d5c86042)
自行进入对应的文件，改图标或者取消。再自行打包！

**Comment by berebrn** [comment]
> > ![IMG_20230816_002253](https://user-images.githubusercontent.com/140738041/260773845-585c6653-48c6-41e2-a489-bafd0db022d7.jpg)
> > ![IMG_20230816_002631](https://user-images.githubusercontent.com/140738041/260774603-f6bbaf71-4467-4556-a0ac-374de81bf27b.jpg)
> > ![IMG_20230816_002550](https://user-images.githubusercontent.com/140738041/260774632-4663fe94-a6f0-4707-856e-d877f0280289.jpg)
> 
> 你手机这emoji库不全呀

![Screenshot_2023-08-16-05-39-49-270_com android settings](https://github.com/constanline/XQuickEnergy/assets/140738041/7abc8eae-a72d-4423-be4b-1b04ca34407e)
钉子户😂

**Comment by Zhangfanyu1222** [comment]
别，看着很好看的，您自己删吧。

**Comment by berebrn** [comment]
> 别，看着很好看的，您自己删吧。
这是我个人问题与大家无关

**Comment by constanline** [comment]
> > 这是我个人问题与大家无关

要不你试试有近似的你手机可以展示的emoji，我替换上去

**Comment by LazyImmortal** [comment]
> > > ![IMG_20230816_002253](https://user-images.githubusercontent.com/140738041/260773845-585c6653-48c6-41e2-a489-bafd0db022d7.jpg)
> > > ![IMG_20230816_002631](https://user-images.githubusercontent.com/140738041/260774603-f6bbaf71-4467-4556-a0ac-374de81bf27b.jpg)
> > > ![IMG_20230816_002550](https://user-images.githubusercontent.com/140738041/260774632-4663fe94-a6f0-4707-856e-d877f0280289.jpg)
> > 
> > 
> > 你手机这emoji库不全呀
> 
> ![Screenshot_2023-08-16-05-39-49-270_com android settings](https://user-images.githubusercontent.com/140738041/260848888-7abc8eae-a72d-4423-be4b-1b04ca34407e.png) 钉子户😂

小米6官方最新版本不是安卓9的MIUI12吗？你这都不是钉子了，而是不愿意升级的老顽固呀……

**Comment by berebrn** [comment]
> > > 这是我个人问题与大家无关
> 
> 要不你试试有近似的你手机可以展示的emoji，我替换上去

![23859](https://github.com/constanline/XQuickEnergy/assets/140738041/5ed8624c-dcfe-4bc3-a56a-103c11da52bb)
偷能量🌳
![23525](https://github.com/constanline/XQuickEnergy/assets/140738041/0313b1cf-6d21-4598-8695-1017804c1220)
投喂小鸡🥗
![23443](https://github.com/constanline/XQuickEnergy/assets/140738041/fa86fbc9-b49d-4a1e-971f-639e3d4fe4c7)
庄园小电视📺
其他的任务图标我没看到，不知道怎么样的，上面这些在搜狗数据文件夹拉出来的

**Comment by berebrn** [comment]
> > > > ![IMG_20230816_002253](https://user-images.githubusercontent.com/140738041/260773845-585c6653-48c6-41e2-a489-bafd0db022d7.jpg)
> > > > ![IMG_20230816_002631](https://user-images.githubusercontent.com/140738041/260774603-f6bbaf71-4467-4556-a0ac-374de81bf27b.jpg)
> > > > ![IMG_20230816_002550](https://user-images.githubusercontent.com/140738041/260774632-4663fe94-a6f0-4707-856e-d877f0280289.jpg)
> > > 
> > > 
> > > 你手机这emoji库不全呀
> > 
> > 
> > ![Screenshot_2023-08-16-05-39-49-270_com android settings](https://user-images.githubusercontent.com/140738041/260848888-7abc8eae-a72d-4423-be4b-1b04ca34407e.png) 钉子户😂
> 
> 小米6官方最新版本不是安卓9的MIUI12吗？你这都不是钉子了，而是不愿意升级的老顽固呀……

老是老了，将就将就😎

**Comment by constanline** [comment]
> 📺

好像不对

**Comment by berebrn** [comment]
> > 📺
> 
> 好像不对

我这边看不到是什么图形，自己默认的😂

**Comment by berebrn** [comment]
[图标.zip](https://github.com/constanline/XQuickEnergy/files/12406768/default.zip)

**Comment by berebrn** [comment]
都是小问题，可以不管的，让大佬搞来搞去的麻烦。

**Comment by constanline** [comment]
到讨论区发吧。你可以试试编辑txt文档，用输入法打出emoji符合，看看那个展示正常
