### ISSUE TITLE
收取间隔问题

### ISSUE THREAD

**Issue by cwj851** [constanline/XQuickEnergy#19]
`` private static int collectEnergy(ClassLoader loader, String userId, long bubbleId, String userName, String bizNo) {
        int collected = 0;
        if (checkCollectLimited()) {
            return 0;
        }
        try {
            String s = "{\"resultCode\": \"FAILED\"}";
            if (Config.collectTimeout() > 0) {
                synchronized (collectLock) {
                    while (System.currentTimeMillis() - lastCollectTime < Config.collectTimeout()) {
                        Thread.sleep(System.currentTimeMillis() - lastCollectTime);
                    }
                    if (Config.doubleCard() && doubleEndTime < System.currentTimeMillis() &&
                            TimeUtil.getTimeStr().compareTo("0700") > 0 && TimeUtil.getTimeStr().compareTo("0725") < 0) {
                        useDoubleCard();
                    }
                    s = AntForestRpcCall.collectEnergy(null, userId, bubbleId);
                    lastCollectTime = System.currentTimeMillis();
                }
            }
            JSONObject jo = new JSONObject(s);
            if (jo.getString("resultCode").equals("SUCCESS")) {
                offerCollectQueue();
                JSONArray jaBubbles = jo.getJSONArray("bubbles");
                jo = jaBubbles.getJSONObject(0);
                collected += jo.getInt("collectedEnergy");
                if (collected > 0) {
                    totalCollected += collected;
                    Statistics.addData(Statistics.DataType.COLLECTED, collected);
                    String str = "偷取【" + userName + "】的能量【" + collected + "克】";
                    Log.forest(str);
                    AntForestToast.show(str);
                } else {
                    Log.recordLog("偷取【" + userName + "】的能量失败", "，UserID：" + userId + "，BubbleId：" + bubbleId);
                }
                if (doubleEndTime > System.currentTimeMillis() && jo.getBoolean("canBeRobbedAgain")) {
                    collected += collectEnergy(loader, userId, bubbleId, userName, null);
                }
                if (bizNo == null || bizNo.isEmpty())
                    return collected;
                int returnCount = 0;
                if (Config.returnWater33() > 0 && collected >= Config.returnWater33())
                    returnCount = 33;
                else if (Config.returnWater18() > 0 && collected >= Config.returnWater18())
                    returnCount = 18;
                else if (Config.returnWater10() > 0 && collected >= Config.returnWater10())
                    returnCount = 10;
                if (returnCount > 0)
                    returnFriendWater(loader, userId, userName, bizNo, 1, returnCount);
            } else {
                Log.recordLog("【" + userName + "】" + jo.getString("resultDesc"), s);
            }
        } catch (Throwable t) {
            Log.i(TAG, "collectEnergy err:");
            Log.printStackTrace(TAG, t);
        }
        return collected;
    }

这里的Config.collectTimeout()是不是应该是收取间隔的Config.collectInterval()而不是收取超时

**Comment by constanline** [comment]
是的，谢谢提醒
