### ISSUE TITLE
1.1.1更新后就通知栏可以被删除了

### ISSUE THREAD

**Issue by Qingchengg** [constanline/XQuickEnergy#191]
> > 
> 
> 已更新，通知消息恢复了，谢谢作者

![image](https://github.com/constanline/XQuickEnergy/assets/34029504/4204156e-bd93-4c7a-9af0-fe85acc5b84c)
你们这好了，之前别人提的会被杀掉问题又出现了。。。
报下手机品牌型号吧，我查查有没有相关的适配信息

_Originally posted by @constanline in https://github.com/constanline/XQuickEnergy/issues/141#issuecomment-1679836307_

**Comment by luzilong520** [comment]
红米手机也有这个问题，型号是Redmi Note 12 Turbo

**Comment by Liujishou** [comment]
不用统计了，是更新关闭了onGoing。！

**Comment by constanline** [comment]
没找到相关的文档，今天加个开关大家自己设置吧。

**Comment by Gu888** [comment]
更新后多数是变成了通知栏可以删除，少数说不显示的是MIUI版本的锅。

**Comment by constanline** [comment]
v1.1.2会增加ongoing开关
