### ISSUE TITLE
安装目录下大量生成runtime.log

### ISSUE THREAD

**Issue by dsjun007** [constanline/XQuickEnergy#193]
安装目录下大量生成runtime.log，删除了又出现了，很占空间
![IMG_20230816_144111](https://github.com/constanline/XQuickEnergy/assets/139686773/95180caf-0015-42b3-91a5-55ed95cba927)

**Comment by chicmr** [comment]
因为之前日志文件是有超过30m自动删除的，导致有bug的时候日志经常被超限删除了，所以作者改成了超30m自动备份就成这样了。

**Comment by chicmr** [comment]
重点还是要简化下日志的输出，不然文件总会很大

**Comment by TikTokJTT** [comment]
我的内存根本花不完，建议作者出个日志增量版和简化版，内存足够且愿意配合作者收集Bug的可以下载增量版。

**Comment by laogao001** [comment]
public static void append2RuntimeLogFile(String s) {
        synchronized (getRuntimeLogFile()) {
            if (getRuntimeLogFile().length() > 31_457_280) {// 30MB
                getRuntimeLogFile().renameTo(getRuntimeLogFileBak());
                if (getRuntimeLogFile().exists()) {
                    getRuntimeLogFile().delete();
                }
            }
            append2File(Log.getFormatDateTime() + "  " + s + "\n", getRuntimeLogFile());
        }
    }

**Comment by Zhangfanyu1222** [comment]
你把/util/FileUtils.java文件往回改就好了，然后自己打包一下。
![图片](https://github.com/constanline/XQuickEnergy/assets/65014915/2d65076c-ee3b-43e6-871a-053ebad61406)

**Comment by Zhangfanyu1222** [comment]
你把/FileUtils.java文件往回改就好了，然后自己打包一下。
![图片](https://github.com/constanline/XQuickEnergy/assets/65014915/da34b725-42a0-4240-acb0-4fefd231d6f2)

**Comment by dsjun007** [comment]
> 你把/FileUtils.java文件往回改就好了，然后自己打包一下。 ![图片](https://user-images.githubusercontent.com/65014915/260976490-da34b725-42a0-4240-acb0-4fefd231d6f2.png)

这种自己改了代码打包容易出错，要么就是安装了支付宝无限重启

**Comment by constanline** [comment]
v1.1.2版本会加入备份开关
