### ISSUE TITLE
1.1.2好友浇水列表点击闪退

### ISSUE THREAD

**Issue by Cgccvhgvhvv** [constanline/XQuickEnergy#201]
1.1.2，好友浇水列表，点击好友后闪退，试了几次都闪退。又去不收能量白名单看了看，不闪退，再回到好友浇水列表，不闪退了，但是点击了几个不同好友，弹出来的框都是同一个好友。

**Comment by TikTokJTT** [comment]
测试了一下雀石会出现这个问题

**Comment by luzilong520** [comment]
Redmi Note 12 Turbo点击合种浇水列表也会闪退

**Comment by cwj851** [comment]
![image](https://github.com/constanline/XQuickEnergy/assets/53599391/8df4f7bd-5ba4-4f5c-bf67-3fcd98f4b8dd)
这两行代码挪到if上面就好了

**Comment by cwj851** [comment]
![image](https://github.com/constanline/XQuickEnergy/assets/53599391/ce3cba4c-1589-4e33-afa1-a235ebe77c5a)
这个文件里的

**Comment by Cgccvhgvhvv** [comment]
> ![image](https://user-images.githubusercontent.com/53599391/261469726-ce3cba4c-1589-4e33-afa1-a235ebe77c5a.png) 这个文件里的

好的，我试试
