### ISSUE TITLE
每日双击卡次数限制无效

### ISSUE THREAD

**Issue by Cgccvhgvhvv** [constanline/XQuickEnergy#205]
如题，设置了每日双击卡次数限制6，但是设置无效，在设置使用双击时间段内无限使用双击卡。

**Comment by Cgccvhgvhvv** [comment]
1.1.2版本。如图所示，设置的早晨7点到7点半双击卡，限制6个。但实际从7点到7点半一直使用双击卡，数了数今天用370多个双击卡。
![Screenshot_2023-08-18-08-24-26-427_pansong291 xposed quickenergy repair](https://github.com/constanline/XQuickEnergy/assets/86583809/0e4f7fd9-ebba-4d91-bb77-113155525411)
/
![Screenshot_2023-08-18-08-24-32-631_pansong291 xposed quickenergy repair](https://github.com/constanline/XQuickEnergy/assets/86583809/2eb34dda-dcb0-48ba-a3b9-936380be3fc1)
![IMG_20230818_082527](https://github.com/constanline/XQuickEnergy/assets/86583809/dca7a0d1-6159-4121-8906-0cf757212a4a)
![Uploading IMG_20230818_082602.jpg…]()

**Comment by cwj851** [comment]
一张双击卡持续5分钟 日志里的[双击卡]代表的是这个能量是双击卡偷得 并不是使用双加卡，你去看看你的背包 少了370多张双击卡吗？

**Comment by Cgccvhgvhvv** [comment]
> 一张双击卡持续5分钟 日志里的[双击卡]代表的是这个能量是双击卡偷得 并不是使用双加卡，你去看看你的背包 少了370多张双击卡吗？

原来一张双击卡能用5分钟啊，那就是我理解错误了，之前没了解过双击卡，虚惊一场*^O^*
370多个我是数的日志记录-.-
