### ISSUE TITLE
日志开了，但是只有好友统计有数据，森林、庄园、其他记录都为空，首页上方的记录也为空。该如何解决呀？

### ISSUE THREAD

**Issue by seafishcosmos** [constanline/XQuickEnergy#207]
日志开了，但是只有好友统计有数据，森林、庄园、其他记录都为空，首页上方的记录也为空。该如何解决呀？存储的权限都给了，始终允许的。
另外气泡提示选了关闭，但是还是会跳提示，怎么关也关不掉。
![微信图片_20230818102321](https://github.com/constanline/XQuickEnergy/assets/103304609/ef0cd4ce-3824-489d-aa8d-b7208f34c544)
![微信图片_20230818102336](https://github.com/constanline/XQuickEnergy/assets/103304609/14541a10-c1dc-426c-bce5-33dd55980015)
![微信图片_202308181023364](https://github.com/constanline/XQuickEnergy/assets/103304609/aaf328f0-e632-4209-b047-0eaca00ddc15)
![微信图片_20230818102335](https://github.com/constanline/XQuickEnergy/assets/103304609/f7c563fa-c77b-47ce-818d-e3d378ea2a79)
![微信图片_202308181023361](https://github.com/constanline/XQuickEnergy/assets/103304609/bafe2cc2-aae8-4410-b99d-a2c6c20e3aaa)
![微信图片_202308181023362](https://github.com/constanline/XQuickEnergy/assets/103304609/e60f55c6-4ee3-4028-8cdb-310065483380)

**Comment by constanline** [comment]
权限问题，给予读写文件权限。

**Comment by seafishcosmos** [comment]
> 权限问题，给予读写文件权限。

![微信图片_20230818104725](https://github.com/constanline/XQuickEnergy/assets/103304609/9be31514-f91e-4c8a-a92f-804ed2330dfe)
感谢回复！权限应该是给了的，RE里面看到这几个文件都是RW的和好友统计那个log是一样的权限。

**Comment by constanline** [comment]
改成rw-rw-rw-(也就是666)试试看，第三组代表非创建者所在组的用户权限。

**Comment by seafishcosmos** [comment]
> 改成rw-rw-rw-(也就是666)试试看，第三组代表非创建者所在组的用户权限。

MT和RE都改不了，提示无法修改内置存储的权限。

**Comment by constanline** [comment]
那把forest.log、farm.log、other.log、statistics.json删掉，再重启支付宝试试看。另外你确认过支付宝的存取权限了吗

**Comment by seafishcosmos** [comment]
> 那把forest.log、farm.log、other.log、statistics.json删掉，再重启支付宝试试看。另外你确认过支付宝的存取权限了吗

谢谢大佬！目前forest.log\farm.log\other.log\statisiics.json已正常。删除之后重启支付宝，不能一进xqe就看里面的日志，要等xqe操作过，自动生成过日志，才能正常显示。
目前就是app没有读取到设置的内容，设置改后可以保存，但是APP好像没读取到最新的设置。还是按照原始的设置在执行。目前气泡提示无法取消，庄园会自动用加速卡和新蛋卡。

**Comment by constanline** [comment]
先让支付宝生成config，然后再从程序修改试试看
