### ISSUE TITLE
Download目录存放配置效果依然不佳，大家有什么好的建议吗

### ISSUE THREAD

**Issue by constanline** [constanline/XQuickEnergy#208]
前几个版本开始改用Download目录作为存放配置的目录，为了解决google高API版本支付宝存储隔离的问题，但是依然很多反馈App与支付宝无法获取存取权限的问题。主要表现在：

1、芝麻粒无权限，设置无效（修改设置项后，再次进入还是原值）等
2、支付宝无权限，无法读取配置，无法写入日志、统计等

而且最重要的是我手机复现不了，所以调试非常困难。本人非安卓开发人员，对于这种问题毫无头绪，请问大家有什么好的建议吗

**Comment by LazyImmortal** [comment]
无法写入日志等，是因为有些用户原本就使用了存储空间隔离，然后在存储路径移动到Download后没有进行更改，导致支付宝没有办法读写隔离中的Download目录吧？

**Comment by LazyImmortal** [comment]
让用户在反馈读写问题的时候，注明支付宝版本，芝麻粒版本、以及是否有使用存储空间隔离等情况。有时候一些问题不一定是芝麻粒本身产生的，也有可能是用户环境的缘故。

**Comment by cwj851** [comment]
让他们不要用google版支付宝完美解决

**Comment by luckyzyx** [comment]
XSP有考虑吗

**Comment by wanwan411** [comment]
我用的原版支付宝，有时候改了设置之后也会变回去，我没法复现

**Comment by Aitanquercus** [comment]
使用存储空间隔离，对支付宝重定向到芝麻粒目录

**Comment by LazyImmortal** [comment]
> 使用存储空间隔离，对支付宝重定向到芝麻粒目录，使用存储空间隔离之后，芝麻粒就可以写入日志、统计了，软件目录，一般不需要放到Download文件夹里面，xqe文件夹，还放在根目录就可以

你这不就是不会善用存储空间隔离吗？都符合标准了，还隔离芝麻粒干什么？直接取消对芝麻粒的隔离，然后允许支付宝访问Download文件夹就行了。

**Comment by berebrn** [comment]
我本人使用官方最新版支付宝，原版xp，操作系统miui9，目前运行正常，个别小问题不影响

**Comment by ww176883** [comment]
1.0开始的三个版本都出现闪退,直接登录不了支付宝,一打开就闪退,看日志只有几个successfully
机型小米安卓13

**Comment by Autines** [comment]
Google商店最新支付宝，配上最新芝麻粒，读写没有问题。
红米刷的PEP13的系统版本

**Comment by Aitanquercus** [comment]
> > 使用存储空间隔离，对支付宝重定向到芝麻粒目录，使用存储空间隔离之后，芝麻粒就可以写入日志、统计了，软件目录，一般不需要放到Download文件夹里面，xqe文件夹，还放在根目录就可以
> 
> 你这不就是不会善用存储空间隔离吗？都符合标准了，还隔离芝麻粒干什么？直接取消对芝麻粒的隔离，然后允许支付宝访问Download文件夹就行了。

不用隔离芝麻粒，使用存储空间隔离，隔离支付宝，让支付宝重定向到芝麻粒文件夹，然后支付宝就可以访问芝麻粒文件夹，然后存储日志、统计了

**Comment by aeromate** [comment]
> 让他们不要用google版支付宝完美解决

安卓13系统+LSpatch，支付宝谷歌版10.2.51.8000没有读写权限问题，只是收能量一会儿就不收了（关闭了收取限制）

**Comment by cls-292** [comment]
服务器存储，或用某云服务盘?，做本地文件读写存储的话要兼容这么多设备品牌，不过配置文件频繁读写可以考虑统一一个地方管理，用API请求获取

**Comment by constanline** [comment]
> 让用户在反馈读写问题的时候，注明支付宝版本，芝麻粒版本、以及是否有使用存储空间隔离等情况。有时候一些问题不一定是芝麻粒本身产生的，也有可能是用户环境的缘故。

回头写个提交问题的模板

**Comment by constanline** [comment]
> 让他们不要用google版支付宝完美解决

666666

**Comment by constanline** [comment]
> XSP有考虑吗

XSP是什么？

**Comment by constanline** [comment]
> 我用的原版支付宝，有时候改了设置之后也会变回去，我没法复现

之前有的版本有问题，确认是同一个版本吗

**Comment by constanline** [comment]
> 使用存储空间隔离，对支付宝重定向到芝麻粒目录，使用存储空间隔离之后，芝麻粒就可以写入日志、统计了，软件目录，一般不需要放到Download文件夹里面，xqe文件夹，还放在根目录就可以

不是普遍使用的

**Comment by constanline** [comment]
> 1.0开始的三个版本都出现闪退,直接登录不了支付宝,一打开就闪退,看日志只有几个successfully 机型小米安卓13

闪退请不要这反馈，另外要发闪退日志。

**Comment by constanline** [comment]
> 1.0开始的三个版本都出现闪退,直接登录不了支付宝,一打开就闪退,看日志只有几个successfully 机型小米安卓13

闪退请不要这反馈，另外要发闪退日志。

**Comment by constanline** [comment]
> > 让他们不要用google版支付宝完美解决
> 
> 安卓13系统+LSpatch，支付宝谷歌版10.2.51.8000没有读写权限问题，只是收能量一会儿就不收了（关闭了收取限制）

请不要在这反馈，另外反馈这个请带上日志

**Comment by constanline** [comment]
> 服务器存储，或用某云服务盘?，做本地文件读写存储的话要兼容这么多设备品牌，不过配置文件频繁读写可以考虑统一一个地方管理，用API请求获取

上传云不太合适，配置文件可能包含一些隐私信息。光配置文件到还好，写日志、统计文件这块感觉不太好处理

**Comment by cls-292** [comment]
> 

那就做个自定义日志和配置文件存储位置

**Comment by cls-292** [comment]
> A

> > 服务器存储，或用某云服务盘?，做本地文件读写存储的话要兼容这么多设备品牌，不过配置文件频繁读写可以考虑统一一个地方管理，用API请求获取
> 
> 上传云不太合适，配置文件可能包含一些隐私信息。光配置文件到还好，写日志、统计文件这块感觉不太好处理

那就做个自定义日志和配置文件存储位置

**Comment by constanline** [comment]
> 那就做个自定义日志和配置文件存储位置

![07195761](https://github.com/constanline/XQuickEnergy/assets/34029504/70f032a2-1078-41d7-bb93-db09b29ad413)
首先这个自定义的存储位置就要存在某个地方啊

**Comment by dsjun007** [comment]
我最新版的支付宝，用着都正常

**Comment by acooler15** [comment]
要不写入数据目录，app增加导入导出功能？

**Comment by mapleshadow** [comment]
> > > 使用存储空间隔离，对支付宝重定向到芝麻粒目录，使用存储空间隔离之后，芝麻粒就可以写入日志、统计了，软件目录，一般不需要放到Download文件夹里面，xqe文件夹，还放在根目录就可以
> > 
> > 
> > 你这不就是不会善用存储空间隔离吗？都符合标准了，还隔离芝麻粒干什么？直接取消对芝麻粒的隔离，然后允许支付宝访问Download文件夹就行了。
> 
> 不用隔离芝麻粒，使用存储空间隔离，隔离支付宝，让支付宝重定向到芝麻粒文件夹，然后支付宝就可以访问芝麻粒文件夹，然后芝麻粒就可以存储日志、统计了

芝麻粒就没有自己的文件夹，何来重定向，应该是赋予支付宝访问标准Download文件夹的权限才对。

**Comment by dsjun007** [comment]
您好，来信已收到！
