### ISSUE TITLE
步数同步失效了？

### ISSUE THREAD

**Issue by xiaoqi2020** [constanline/XQuickEnergy#209]
从 1.1.0 开始，步数就失效了，不知是不是我一个人才有这个情况！

**Comment by LazyImmortal** [comment]
没失效

**Comment by aeromate** [comment]
听说步数同步是在点钟，感觉不符合常理，所以都没开过，建议增加同步步数范围和时间设置。

**Comment by Khaos116** [comment]
步数好像没有自动兑换使用，我用之前的XQ和小新好像是可以自动兑换的
