### ISSUE TITLE
1.1.2版本森林点击净滩行动列表闪退

### ISSUE THREAD

**Issue by sundongxiao** [constanline/XQuickEnergy#210]
https://github.com/constanline/XQuickEnergy/assets/33159212/762636fe-e0e3-4ee4-a26d-def0c692ea29

**Comment by sundongxiao** [comment]
配置文件及log如下：
[xqe配置及log.zip](https://github.com/constanline/XQuickEnergy/files/12376261/xqe.log.zip)

**Comment by LazyImmortal** [comment]
https://github.com/constanline/XQuickEnergy/issues/201#issuecomment-1683157543

**Comment by Cgccvhgvhvv** [comment]
> [#201 (comment)](https://github.com/constanline/XQuickEnergy/issues/201#issuecomment-1683157543)

按[cwj851](https://github.com/cwj851)大佬的方法挪动那两行代码后完美解决，刚试了试净摊列表不闪退。

**Comment by sundongxiao** [comment]
[xqe-sesame-v1.1.2.zip](https://github.com/constanline/XQuickEnergy/files/12377426/xqe-sesame-v1.1.2.zip)
挪动那两行代码后完美解决
