### ISSUE TITLE
期望适配底部小横条颜色

### ISSUE THREAD

**Issue by Autines** [constanline/XQuickEnergy#211]
辛苦大佬，期望能适配底部横条颜色，现在是黑底。😁

**Comment by dsjun007** [comment]
黑底？帖张图撒，现在的界面很漂亮啊

**Comment by HuiNIMA** [comment]
![Screenshot_2023-08-18-23-13-57-427_pansong291 xposed quickenergy repair](https://github.com/constanline/XQuickEnergy/assets/33143156/91721d50-b06e-4b8a-a214-22f99eda169f)
不黑啊，挺好看的

**Comment by Autines** [comment]
![微信图片_20230819111223](https://github.com/constanline/XQuickEnergy/assets/16075324/f83aefa0-3d5c-470f-b9c5-8800c34f8c90)

**Comment by constanline** [comment]
改成绿色了，但是我感觉原版就挺好看的。
