### ISSUE TITLE
古树保护存在漏一颗的问题

### ISSUE THREAD

**Issue by lowbibi** [constanline/XQuickEnergy#212]
如题，古树保护时会间歇性的出现漏掉一颗古树不自动保护的问题，这个bug我遇到好几次了，有时会在我中午打开支付宝后自动补上，有时就不行，刚刚去看了一下日志发现杭州有一颗没有保护，不知道是不是我个人手机问题？

**Comment by Cgccvhgvhvv** [comment]
确实有这个问题，下午重启了一下支付宝，显示又保护一棵古树

**Comment by berebrn** [comment]
我遇到是需要手动滑动验证

**Comment by luzilong520** [comment]
是有这个问题

**Comment by constanline** [comment]
发runtime日志看下
