### ISSUE TITLE
芝麻粒结束进程打开，我知道了的弹窗就会弹出。

### ISSUE THREAD

**Issue by sundongxiao** [constanline/XQuickEnergy#215]
![863822755e6be5b181f9f4556a4b2ce](https://github.com/constanline/XQuickEnergy/assets/33159212/005c3a63-0cdc-44d0-b0a9-70adf7bdda14)
每次芝麻粒结束进程再打开，我知道了的弹窗就会弹出。希望增加一个不再提示勾选框。

**Comment by Cgccvhgvhvv** [comment]
#82

**Comment by LazyImmortal** [comment]
一个弹窗又不是多麻烦，但是责任问题必须撇清。

**Comment by WenRou-Pan** [comment]
可以自己把代码删了然后打包，代码在MainActivity，也可以用仙人掌，我的仓库有打包好的
