### ISSUE TITLE
建议增加账户切换检测功能

### ISSUE THREAD

**Issue by Gasonylq** [constanline/XQuickEnergy#216]
手动切换账号后，不会执行自动收取能量等任务，需要强制关闭支付宝再启动才可以，建议增加手动切换账户时的检测。

**Comment by WenRou-Pan** [comment]
可以自己把代码删了然后打包，代码在MainActivity，也可以用仙人掌，我的仓库有打包好的

**Comment by luzilong520** [comment]
现在就是这个问题，必须要强制关了支付宝重新进才会检测

**Comment by cwj851** [comment]
早就改了 都好几个版本了 切号自动重新加载插件

**Comment by pctit** [comment]
> 早就改了 都好几个版本了 切号自动重新加载插件

对的 最新的几版都没什么问题

**Comment by dsjun007** [comment]
前几个版本起就有了，感觉离添加小号功能不远了
