### ISSUE TITLE
1.1.2-fix1通知栏不显示收能量

### ISSUE THREAD

**Issue by Cgccvhgvhvv** [constanline/XQuickEnergy#220]
如图所示，通知栏不显示收能量，降回1.1.2正常显示
![IMG_20230818_225508](https://github.com/constanline/XQuickEnergy/assets/86583809/040f1a49-a128-4383-9132-405827aaaabd)
![IMG_20230818_225702](https://github.com/constanline/XQuickEnergy/assets/86583809/a4ae1afd-f083-4fa5-969b-ebd2a9b4a839)

**Comment by luzilong520** [comment]
撤包了，应该包有问题

**Comment by constanline** [comment]
1.1.2-fix1并没有发包
