### ISSUE TITLE
关于施肥0.01

### ISSUE THREAD

**Issue by yucotang** [constanline/XQuickEnergy#222]
希望可以增加当检测到施肥异常，每次涨幅0.01的时候可以停止施肥的功能![Screenshot_2023-08-19-07-46-44-324_pansong291.xposed.quickenergy.repair.jpg](https://github.com/constanline/XQuickEnergy/assets/74399055/04e9d340-3ad1-4d33-b806-7bd27ce2de4e)

**Comment by constanline** [comment]
#206
