### ISSUE TITLE
支付宝芝麻粒卡死

### ISSUE THREAD

**Issue by 1Hecate** [constanline/XQuickEnergy#228]
1.1.2fix2版本点击设置按钮会直接卡死，支付宝也会直接白屏卡死，结束两个软件或重启手机都无法解决，lsp关闭芝麻粒后支付宝才能正常运行，开启支付宝还是卡死

**Comment by 1Hecate** [comment]
删除xqe文件夹后重装芝麻粒解决了

**Comment by FunctionXJB** [comment]
删除xqe文件夹后，重新配置好友浇水克数和合种浇水克数时候总是闪退，安卓11，1.1.2-fix2，支付宝10.3.36.7200

**Comment by shaoying189** [comment]
我试了好几个版本支付宝，芝麻粒分身内的设置，都是卡死，等几秒后闪退

**Comment by berebrn** [comment]
> 删除xqe文件夹后，重新配置好友浇水克数和合种浇水克数时候总是闪退，安卓11，1.1.2-fix2，支付宝10.3.36.7200

删除xqe文件前，备份config.json。这个是配置文件

**Comment by shaoying189** [comment]
> 

一样的，我从1.0.8升1.1.2，芝麻粒就正常

**Comment by berebrn** [comment]
> 

降版本咯，等修复好了再更新。我不用分身不了解

**Comment by constanline** [comment]
v1.1.3已修复
