### ISSUE TITLE
能量收取还是会自动停下，不好意思，再次反馈了

### ISSUE THREAD

**Issue by dsjun007** [constanline/XQuickEnergy#231]
能量收取还是会自动停下，miui14，root，lsp
![IMG_20230820_145943](https://github.com/constanline/XQuickEnergy/assets/139686773/1c5f4dbb-42cc-494e-b447-b5cd0dcef5bd)
![IMG_20230820_150613](https://github.com/constanline/XQuickEnergy/assets/139686773/c3ea617a-de12-465b-826a-2a3764e1361b)
![IMG_20230820_150735](https://github.com/constanline/XQuickEnergy/assets/139686773/19d0cd11-5afa-4af0-bd04-cb45c51cf626)

**Comment by Liujishou** [comment]
带上runtime.log，方便定位问题。

**Comment by dsjun007** [comment]
> 带上runtime.log，方便定位问题。

日志备份关了，刚查看前面的记录已经没有了

**Comment by dsjun007** [comment]
检测时间间隔2分钟，其他默认，早上自己的能量球不手动收都被别人收了

**Comment by xiaoqi2020** [comment]
我的也一样，状态栏虽然一直显示下一次检测是多久，到实际上并没有工作！

**Comment by berebrn** [comment]
> 检测时间间隔2分钟，其他默认，早上自己的能量球不手动收都被别人收了

间隔2分钟，太频繁了。高峰时段程序还没有跑完又重新检测容易异常，建议设置5-10分钟！

**Comment by dsjun007** [comment]
> 

间隔时间长了自己的能量球都收不到

**Comment by berebrn** [comment]
> > 
> 
> 间隔时间长了自己的能量球都收不到

![Screenshot_2023-08-20-21-42-28-625_pansong291 xposed quickenergy repair](https://github.com/constanline/XQuickEnergy/assets/140738041/77c25bd2-b5f5-45f0-8705-c8031a4cc78d)
保一块地有200活力，明天兑换一个保护罩就行了，我是每天0点后兑换

**Comment by KANHUYIZHIGOU** [comment]
2分钟检测是不是真的有问题啊？一千个小号，一次检测出3000个球？一次可以检测出多少球啊？12分钟好像挺稳的

**Comment by berebrn** [comment]
> 2分钟检测是不是真的有问题啊？一千个小号，一次检测出3000个球？一次可以检测出多少球啊？12分钟好像挺稳的

这样说你去看runtime.log，2分钟程序是跑不完的

**Comment by constanline** [comment]
新版还有问题吗，有问题的话上传下日志，没反馈的话我就关了
