### ISSUE TITLE
请问收取能量开关是不是与送水功能一起的？

### ISSUE THREAD

**Issue by biily24** [constanline/XQuickEnergy#24]
1，芝麻粒我只开了能量雨和送水功能，能量雨能正常工作，但是送水功能无法启动，是不是必须开启收取能量，送水才会工作，建议分开
2，一个支付宝切换账号的时候，芝麻粒无法工作，要把支付宝退出，重新进入，芝麻粒才会重新启动，这个是bug吗，还是后台进程机制的问题？

**Comment by constanline** [comment]
如果依然觉得有问题的话，明天联系看下日志。q群 824172228

**Comment by constanline** [comment]
> 1，芝麻粒我只开了能量雨和送水功能，能量雨能正常工作，但是送水功能无法启动，是不是必须开启收取能量，送水才会工作，建议分开 2，一个支付宝切换账号的时候，芝麻粒无法工作，要把支付宝退出，重新进入，芝麻粒才会重新启动，这个是bug吗，还是后台进程机制的问题？

今天有群友反馈，问题确实存在，是我的锅。
![image](https://github.com/constanline/XQuickEnergy/assets/34029504/a0c0eae3-15f5-438b-81d8-20383f45b4b0)
看过日志后发现，selfId指当前用户id，但是这个id是在收能量的第一步获取的。因此如果不打开收能量开关就无法浇水，此问题将在107版修复。

**Comment by biily24** [comment]
> 

谢谢大神
