### ISSUE TITLE
[Questions and Bugs Report] (Android14开启模块启动支付宝卡死)

### ISSUE THREAD

**Issue by nonepage** [constanline/XQuickEnergy#244]
### Module App version / 模块版本

1.3

### Device model and system in used / 正在使用的设备型号以及使用的系统

miui

### Android version / Android 版本

13

### Xposed Framework name and version / Xposed 框架名称与版本号

1.8.6（6976）

### Describe in detail why the problem occurred / 详细描述问题发生的具体原因

最新版lsp支持了Android14，但是模块好像有点问题，希望能解决一下
具体现象为：点击支付宝卡白，设置也点不进去，但昨天升级Android14后fix2版还能用，今天g了，升级1.3也不行

### Provide module problem logs or necessary logs / 提供模块问题 Log 或必要 Log

<details><summary>Click to expand / 展开查看</summary><pre><code>

(Paste problem log here / 此处粘贴问题 Log)

</code></pre></details>

### Confirm the contents you submitted / 确认一下你提交的信息

- [X] I certify that the above contents is correct / 我确保上述信息准确无误

**Comment by constanline** [comment]
需提供闪退、anr日志

**Comment by nonepage** [comment]
1.4可用
