### ISSUE TITLE
新村自动领奖无法打开

### ISSUE THREAD

**Issue by shaoying189** [constanline/XQuickEnergy#255]
### 模块版本

1.1.4

### 正在使用的设备型号以及使用的系统

color os

### Android 版本

13

### Xposed 框架名称与版本号

1.86

### 详细描述问题发生的具体原因

庄园——自动领奖，无发打开
打开返回设置，再次打开设置，庄园——自动领奖还是关闭状态

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by is-xianglei** [comment]
+1同等问题
打开了新村所有的设置，保存后再次查看依旧是没有打开的情况

**Comment by acooler15** [comment]
好像只是界面中显示的没有打开，配置文件`stallReceiveAward`的值是`true`了

**Comment by Liujishou** [comment]
作者漏了添加 sw_stallReceiveAward

**Comment by yucotang** [comment]
刚想反馈看到已经有了，你们速度真快

**Comment by xx668888** [comment]
+1同等问题

**Comment by constanline** [comment]
v1.1.5 会修复
