### ISSUE TITLE
希望庄园增加每日捐蛋功能

### ISSUE THREAD

**Issue by ebuluo816** [constanline/XQuickEnergy#256]
### 增强类型

功能型增强

### 具体描述

希望庄园增加每日捐蛋功能，每天捐献一颗爱心鸡蛋，每月捐15天有奖励.

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by berebrn** [comment]
此功能已经有了

**Comment by LazyImmortal** [comment]
捐赠爱心鸡蛋 就是每日只捐一颗鸡蛋。这个提议你可以关了。

**Comment by 947814157** [comment]
我一百多蛋这两天直接给我卷没了，调了也不起作用诶
