### ISSUE TITLE
a

### ISSUE THREAD

**Issue by rovktt** [constanline/XQuickEnergy#260]

**Comment by berebrn** [comment]
可以关了，去讨论区发表

**Comment by rovktt** [comment]
> ### 增强类型
> 功能型增强
> 
> ### 具体描述
> 建议声明一下，此软件可能导致蚂蚁森林账号异常不能收取能量，介意者缷载本软件手动收取能量。
> 
> ### 确认一下你提交的信息
> * [ ]  我确保上述信息准确无误

**Comment by constanline** [comment]
额？
