### ISSUE TITLE
海洋能量不自动收取

### ISSUE THREAD

**Issue by FunctionXJB** [constanline/XQuickEnergy#261]
### 增强类型

功能型增强

### 具体描述

![Screenshot_2023-08-23-17-44-31-490_com eg android AlipayGphone](https://github.com/constanline/XQuickEnergy/assets/24306353/271e24d0-cf2f-46a8-b51e-f6bc82eddad5)
希望增加单独开关，控制海洋能量收取功能，有些能量只能在海洋收取，森林中不存在

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by WskDnpl** [comment]
作者说了，这个没法做单独的开关，跟森林是一起的，你可以自己手动收下

**Comment by FunctionXJB** [comment]
> 作者说了，这个没法做单独的开关，跟森林是一起的，你可以自己手动收下

不会吧，以我的理解加个if判断开关，来选择执行森林海洋通收或者是目前只收森林的状态

**Comment by Zhangfanyu1222** [comment]
后来的版本都删了海洋收能量，https://github.com/constanline/XQuickEnergy/issues/119#issue-1844304295

**Comment by FunctionXJB** [comment]
> 后来的版本都删了海洋收能量，[#119 (comment)](https://github.com/constanline/XQuickEnergy/issues/119#issue-1844304295)

这个我知道，所以我才希望可以加个开关，使海洋里的能量也能收

**Comment by FunctionXJB** [comment]
> 后来的版本都删了海洋收能量，[#119 (comment)](https://github.com/constanline/XQuickEnergy/issues/119#issue-1844304295)

这个我知道，所以我才希望可以加个开关，使海洋里的能量也能收
