### ISSUE TITLE
希望增加步数修改时间开关

### ISSUE THREAD

**Issue by dsjun007** [constanline/XQuickEnergy#262]
### 增强类型

功能型增强

### 具体描述

系统： MIUI14 Android13
方式： Magisk26.1 + LSPosed1.8.6
版本： 支付宝10.5.10 8000 + 芝麻粒v1.1.3
建议： 目前不知道步数修改什么时间段执行，最近不能同步手机上本来的步数，希望增加步数修改时间开关
谢谢

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by Liujishou** [comment]
目前是06:00后修改

**Comment by aeromate** [comment]
赞同增加开关，自定义步数范围和开启同步时间，主要是早上6点要跑到2w布，毕竟是少数。
如果懒得增加自定义时间，就建议把时间改为下午2点钟也好。
