### ISSUE TITLE
安卓11下日志功能没用

### ISSUE THREAD

**Issue by 965973717** [constanline/XQuickEnergy#263]
### 模块版本

1.1.4

### 正在使用的设备型号以及使用的系统

Hos11，一加7t

### Android 版本

11

### Xposed 框架名称与版本号

LSPosed1.8.6

### 详细描述问题发生的具体原因

安卓11下日志功能没用

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by constanline** [comment]
支付宝权限确认下。另外支付宝用的什么版本

**Comment by 947814157** [comment]
> 支付宝权限确认下。另外支付宝用的什么版本

支付宝需要哪些权限呀

**Comment by 965973717** [comment]
> 

支付宝版本： 10.5.10.8100
权限给了有：存储，位置信息，健身运动，相机。
MT里面看了一下几个log的权限都是660，

**Comment by 965973717** [comment]
> 支付宝权限确认下。另外支付宝用的什么版本

支付宝版本： 10.5.10.8100
权限给了有：存储，位置信息，健身运动，相机。
MT里面看了一下几个log的权限都是660，

**Comment by 965973717** [comment]
> 支付宝权限确认下。另外支付宝用的什么版本

支付宝版本： 10.5.10.8100
权限给了有：存储，位置信息，健身运动，相机。
MT里面看了一下几个log的权限都是660，

**Comment by 947814157** [comment]
我的是8000版本国内的为什么我的就提示是最新版了升级不了这些权限我都给了呢？至于你说的MT里面日志都是660这个我不知道什么意思





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月24日(周四) 凌晨2:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [constanline/XQuickEnergy] 安卓11下日志功能没用 (Issue #263)




  
支付宝权限确认下。另外支付宝用的什么版本
  
支付宝版本： 10.5.10.8100
 权限给了有：存储，位置信息，健身运动，相机。
 MT里面看了一下几个log的权限都是660，

**Comment by 965973717** [comment]
> 我的是8000版本国内的为什么我的就提示是最新版了升级不了这些权限我都给了呢？至于你说的MT里面日志都是660这个我不知道什么意思
> [...](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年8月24日(周四) 凌晨2:26 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [constanline/XQuickEnergy] 安卓11下日志功能没用 (Issue #263) 支付宝权限确认下。另外支付宝用的什么版本 支付宝版本： 10.5.10.8100 权限给了有：存储，位置信息，健身运动，相机。 MT里面看了一下几个log的权限都是660， — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

等作者回复，，刚才我发现回复给你回复错了😂660的意思可读可写但是不能保存，安卓这块我还没学就会个JAVA

**Comment by constanline** [comment]
尝试把runtime、simple日志删掉，然后不要开芝麻粒直接开支付宝。看看能生成日志吗

**Comment by berebrn** [comment]
> 我的是8000版本国内的为什么我的就提示是最新版了升级不了这些权限我都给了呢？至于你说的MT里面日志都是660这个我不知道什么意思
> [...](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年8月24日(周四) 凌晨2:26 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [constanline/XQuickEnergy] 安卓11下日志功能没用 (Issue #263) 支付宝权限确认下。另外支付宝用的什么版本 支付宝版本： 10.5.10.8100 权限给了有：存储，位置信息，健身运动，相机。 MT里面看了一下几个log的权限都是660， — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

![IMG_20230824_085645](https://github.com/constanline/XQuickEnergy/assets/140738041/3b740d60-c572-4d70-b9a5-c7e2d007928e)
![IMG_20230824_085721](https://github.com/constanline/XQuickEnergy/assets/140738041/2c4e71ba-9f67-4e70-bf32-6ec2cafa54a8)

**Comment by 947814157** [comment]
好像确实哦我又在安卓7虚拟机理测试了一下日志什么的都完美运行就是安卓七虚拟机可能有点小卡真机被我搞的现在问题更多了太极，LSPatch我都试了，太极阴这个插件用不了，LSPatch要配合sizhiku且必须root否则不能开机自启还不如应用转生，这些问题都好多，算了先将就虚拟机用着吧，真机的昨晚搞了大晚上各种问题，芝麻粒超时之类的不知道怎么回事很频繁了以前破车还能骑，这些好了直接更破了，变驴车了修的频率更高了，暂时先不折腾了回头看看哪位有同样境况的兄弟整出教程了在搞搞吧





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月24日(周四) 上午8:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [constanline/XQuickEnergy] 安卓11下日志功能没用 (Issue #263)




  
我的是8000版本国内的为什么我的就提示是最新版了升级不了这些权限我都给了呢？至于你说的MT里面日志都是660这个我不知道什么意思
 ...
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年8月24日(周四) 凌晨2:26 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [constanline/XQuickEnergy] 安卓11下日志功能没用 (Issue #263) 支付宝权限确认下。另外支付宝用的什么版本 支付宝版本： 10.5.10.8100 权限给了有：存储，位置信息，健身运动，相机。 MT里面看了一下几个log的权限都是660， — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;

**Comment by 965973717** [comment]
> 尝试把runtime、simple日志删掉，然后不要开芝麻粒直接开支付宝。看看能生成日志吗

日志生成了，但是又不会收能量了，其他功能正常😊

**Comment by 947814157** [comment]
别搞了我都放弃了，越搞问题越多，我试了好多越搞bug越多，算了吧等大佬出教程吧，VX我都试了直接给我闪退黑屏手机好久不反应，也不知道为啥我就用模拟器安卓7的不好吗还可以自己root面具啥的他不香嘛反正奔溃了重新来过，真机搞坏了就变砖了好难搞哦





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月24日(周四) 中午1:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [constanline/XQuickEnergy] 安卓11下日志功能没用 (Issue #263)




  
尝试把runtime、simple日志删掉，然后不要开芝麻粒直接开支付宝。看看能生成日志吗
  
日志生成了，但是又不会收能量了，其他功能正常😊

**Comment by 947814157** [comment]
用虚拟机吧兄弟，问题少就算有问题咱重
来就行了，真机问题又多关键一不小心变砖了麻烦你看看我这截图，真机还经常异常还经常就登陆超时，甚至重启时候还要登陆好烦人呀，我那个农场的浏览任务还经常异常看不到浏览的产品就停止了那个图忘记截图了，反正正常浏览页面应该有两列商品图他就是一片白的，然后写着任务异常，然后就跟死循环一样不知道怎么办了我只好把它强行停止了好烦人好气弄了好几次都这样就不搞了















---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月24日(周四) 中午1:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [constanline/XQuickEnergy] 安卓11下日志功能没用 (Issue #263)




  
尝试把runtime、simple日志删掉，然后不要开芝麻粒直接开支付宝。看看能生成日志吗
  
日志生成了，但是又不会收能量了，其他功能正常😊

**Comment by constanline** [comment]
> > 尝试把runtime、simple日志删掉，然后不要开芝麻粒直接开支付宝。看看能生成日志吗
> 
> 日志生成了，但是又不会收能量了，其他功能正常😊

那把Config文件删掉，依然是由支付宝打开生成。从你目前说的情况来看，是支付宝没有读写芝麻粒生成文件的权限，但是反过来没问题。

**Comment by constanline** [comment]
无新回复，关闭
