### ISSUE TITLE
希望增加早上07:00-07:30仅收取能量的开关

### ISSUE THREAD

**Issue by dsjun007** [constanline/XQuickEnergy#268]
### 增强类型

功能型增强

### 具体描述

系统： MIUI14 Android13
方式： Magisk26.1 + LSPosed1.8.6
版本： 支付宝10.5.10 8000 + 芝麻粒v1.1.3
建议： 希望增加早上07:00-07:30仅收取能量的开关，这个时间段只收能量

**Comment by berebrn** [comment]
可以关了，去讨论区发表

**Comment by LazyImmortal** [comment]
> 可以关了，去讨论区发表

功能建议，又不是寻求答疑解惑，为什么要去讨论区发表？

**Comment by berebrn** [comment]
> > 可以关了，去讨论区发表
> 
> 功能建议，又不是寻求答疑解惑，为什么要去讨论区发表？

这个功能除了你建议使用外，会有多少人使用？

**Comment by Zhangfanyu1222** [comment]
你想在那半个小时，一边收能量一边养鸡？

**Comment by LazyImmortal** [comment]
> > > 可以关了，去讨论区发表
> > 
> > 功能建议，又不是寻求答疑解惑，为什么要去讨论区发表？
> 
> 这个功能除了你建议使用外，会有多少人使用？

首先，我没有建议使用，这个功能我也觉得没有用；其次，大家都有表达诉求的权利，不仅仅是你；最后，功能要不要上是开发者考量的，他没有这个计划就close掉呗。

**Comment by berebrn** [comment]
> > > > 可以关了，去讨论区发表
> > > 
> > > 
> > > 功能建议，又不是寻求答疑解惑，为什么要去讨论区发表？
> > 
> > 
> > 这个功能除了你建议使用外，会有多少人使用？
> 
> 首先，我没有建议使用，这个功能我也觉得没有用；其次，大家都有表达诉求的权利，不仅仅是你；最后，功能要不要上是开发者考量的，他没有这个计划就close掉呗。

有道理☺️

**Comment by cwj851** [comment]
你们确定是芝麻粒的用户吗？现在的逻辑默认就是7-7.30只收能量

**Comment by FunctionXJB** [comment]
目前状态好像就是只收能量其他不干，我个人需求是什么都干，也希望能加个开关

**Comment by Zhangfanyu1222** [comment]
> 目前状态好像就是只收能量其他不干，我个人需求是什么都干，也希望能加个开关

不考虑异常等问题的话，你可以什么都干

**Comment by FunctionXJB** [comment]
> 

目前版本可以实现？应该怎么设置？

**Comment by FunctionXJB** [comment]
> > 目前状态好像就是只收能量其他不干，我个人需求是什么都干，也希望能加个开关
> 
> 不考虑异常等问题的话，你可以什么都干

目前版本可以实现？应该怎么设置？

**Comment by dsjun007** [comment]
> 你们确定是芝麻粒的用户吗？现在的逻辑默认就是7-7.30只收能量

是看了森林日志才问的
07:00:05 森林签到📆
07:00:05 森林任务🧾️[逛一逛花呗花花卡]
07:00:06 森林任务🧾️[逛一逛蚂蚁庄园]
07:00:06 完成任务🧾️[合理设定空调温度]
07:00:07 任务奖励🎖️[逛一逛花呗花花卡]#1个
07:00:08 任务奖励🎖️[逛一逛蚂蚁庄园]#1个
07:00:10 使用道具🎭[限时双击卡]

**Comment by dsjun007** [comment]
> 你们确定是芝麻粒的用户吗？现在的逻辑默认就是7-7.30只收能量

是看了森林日志才问的
07:00:05 森林签到📆
07:00:05 森林任务🧾️[逛一逛花呗花花卡]
07:00:06 森林任务🧾️[逛一逛蚂蚁庄园]
07:00:06 完成任务🧾️[合理设定空调温度]
07:00:07 任务奖励🎖️[逛一逛花呗花花卡]#1个
07:00:08 任务奖励🎖️[逛一逛蚂蚁庄园]#1个
07:00:10 使用道具🎭[限时双击卡]

**Comment by cwj851** [comment]
> > 你们确定是芝麻粒的用户吗？现在的逻辑默认就是7-7.30只收能量
> 
> 是看了森林日志才问的 07:00:05 森林签到📆 07:00:05 森林任务🧾️[逛一逛花呗花花卡] 07:00:06 森林任务🧾️[逛一逛蚂蚁庄园] 07:00:06 完成任务🧾️[合理设定空调温度] 07:00:07 任务奖励🎖️[逛一逛花呗花花卡]#1个 07:00:08 任务奖励🎖️[逛一逛蚂蚁庄园]#1个 07:00:10 使用道具🎭[限时双击卡]

只有森林任务照常执行其他都不会执行，也没有几个任务，感觉不影响收能量，既然要求今天就更新成不执行

**Comment by berebrn** [comment]
![Screenshot_2023-08-24-12-17-22-067_pansong291 xposed quickenergy repair](https://github.com/constanline/XQuickEnergy/assets/140738041/abef9d4f-a0be-43ad-ad24-36de0e764f38)
很稳啊

**Comment by dsjun007** [comment]
> 你想在那半个小时，一边收能量一边养鸡？

那半小时只要收能量

**Comment by dsjun007** [comment]
> ![Screenshot_2023-08-24-12-17-22-067_pansong291 xposed quickenergy repair](https://user-images.githubusercontent.com/140738041/262858888-abef9d4f-a0be-43ad-ad24-36de0e764f38.png) 很稳啊

你这个前五分钟也有暂停收的问题嘛

**Comment by Zhangfanyu1222** [comment]
> > 你想在那半个小时，一边收能量一边养鸡？
> 
> 那半小时只要收能量

那不就结了，默认就是那半小时只收能量不做其他事

**Comment by berebrn** [comment]
![Screenshot_2023-08-24-12-58-35-616_pansong291 xposed quickenergy repair](https://github.com/constanline/XQuickEnergy/assets/140738041/579eff91-957a-454c-bc24-8f62544909f3)
7点-7点半完整版
