### ISSUE TITLE
最新版状态栏bug

### ISSUE THREAD

**Issue by luzilong520** [constanline/XQuickEnergy#274]
### 程序版本 / 框架版本 / 模块版本

LSPatch0.51   模块版本v1.1.6

### 系统版本 / Android版本

MIUI/Android 13

### 详细描述问题发生的具体原因

![Screenshot_2023-08-24-23-14-47-869_com miui home](https://github.com/constanline/XQuickEnergy/assets/83388356/720c6641-aecf-48c2-b868-16f8d9ab7ee1)
状态栏芝麻粒显示不了，一片空白

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by LazyImmortal** [comment]
这不是Bug，多行通知折叠起来了。折叠起来的通知不给下拉按钮，只能通过长按来展开，这是MIUI魔改通知栏的锅，与本应用无关。

**Comment by yucotang** [comment]
> 这不是Bug，多行通知折叠起来了。折叠起来的通知不给下拉按钮，只能通过长按来展开，这是MIUI魔改通知栏的锅，与本应用无关。

确实如你所说，但是1.1.14及之前，芝麻粒的显示是正常的，对比了一下，之前【下次扫描时间……】和芝麻粒几个字是在同一行的，只有2行，现在有3行了，应该是这样造成的![IMG_20230825_011210.jpg](https://github.com/constanline/XQuickEnergy/assets/74399055/932e211f-fd23-4508-8291-b10a3359fbd9)

**Comment by yucotang** [comment]
![IMG_20230825_011210.jpg](https://github.com/constanline/XQuickEnergy/assets/74399055/3fb0ca9d-0067-449b-a7de-99316147da50)

**Comment by LazyImmortal** [comment]
> > 这不是Bug，多行通知折叠起来了。折叠起来的通知不给下拉按钮,只能通过长按来展开,这是MIUI魔改通知栏的锅,与本应用无关。
> 
> 不是改版，1.1.3之前显示是正常的，就是14跟15才这样

不是说1.1.3就正常，后面的通知栏就不正常，后面的通知栏也是正常的。通知抽屉本来就为Notification.InboxStyle提供收缩功能，只是应用之前没用罢了。不显示展开按钮就是MIUI魔改的，求求你用个原生样式通知栏看看吧。
![Screenshot_2023-08-25-01-54-56-872_com.miui.home.png](https://github.com/constanline/XQuickEnergy/assets/44522979/04ddaa7a-6fdc-42da-8cfa-a7d52dc76c10)

**Comment by Angel-Anderson** [comment]
![S30825-07321201_com.android.systemui.png](https://github.com/constanline/XQuickEnergy/assets/139981005/6c0108db-16cd-4de7-aa58-9e6302075f8f)

被系统折叠了，别纠结了

**Comment by zhang-001** [comment]
一样情况、从115开始才这样的

**Comment by ainiyong86** [comment]
一样一样，安卓13，MIUI14，芝麻粒1.1.6下拉也显示空白，只能用原生下拉能看见😥

**Comment by constanline** [comment]
属于正常情况，
之前版本只有MIUI系统能正常显示两行通知栏，其他的系统只能显示一行，会出现“下次扫描时间07:00:00 06:55:33 收：1...”这样的情况。
新版调整为InboxStyle，所有手机展开是均可以看到所有文本。
