### ISSUE TITLE
双开版本不能保存设置

### ISSUE THREAD

**Issue by Jin132087** [constanline/XQuickEnergy#275]
### 程序版本 / 框架版本 / 模块版本

支付宝 10.3.86 LSPosed 1.8.6 模块1.1.6

### 系统版本 / Android版本

Android 11

### 详细描述问题发生的具体原因

LSP里激活双开以后，不会在分身存储里建立文件，也不能保存分身的设置。所有设置均不能保存

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by constanline** [comment]
文件不能创建、配置不能读取、日志打不开，均属于文件读写权限问题。如果可以请使用系统自带的分身而不要用LSP来创建分身！

**Comment by constanline** [comment]
#282

**Comment by acooler15** [comment]
https://github.com/constanline/XQuickEnergy/issues/22#issuecomment-1647294040
#77

**Comment by Jin132087** [comment]
新版本已经可以了
