### ISSUE TITLE
会员签到/商家打卡签到失效

### ISSUE THREAD

**Issue by shaoying189** [constanline/XQuickEnergy#277]
### 程序版本 / 框架版本 / 模块版本

1.86

### 系统版本 / Android版本

color os  13.1

### 详细描述问题发生的具体原因

会员签到/商家打卡签到失效

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by LazyImmortal** [comment]
你连基本信息都懒得填？
