### ISSUE TITLE
芭芭农场，每当施肥升级后，只施肥一次就不继续施肥了

### ISSUE THREAD

**Issue by xzsyz** [constanline/XQuickEnergy#279]
### 程序版本 / 框架版本 / 模块版本

LSPosed 1.8.6      模块版本1.16   1.15

### 系统版本 / Android版本

miui13    Android 12          miui12   Android 10

### 详细描述问题发生的具体原因

芭芭农场，每当施肥升级后，只施肥一次就不继续施肥了，在两部手机上均出现这个情况
![c6b2f562bdc934c1e4664f3cfb6df1a](https://github.com/constanline/XQuickEnergy/assets/143146245/c84108fb-b0c6-4602-af54-5e65ebf92855)
![f9a850dfc61a10e117016c7c69a07ce](https://github.com/constanline/XQuickEnergy/assets/143146245/5526e129-d664-4c73-bdb6-502e947a04d8)

### 提供模块问题 Log 或必要 Log

[Uploading runtime.log…]()

**Comment by constanline** [comment]
今天更新
