### ISSUE TITLE
新村摆餐没有记录显示

### ISSUE THREAD

**Issue by berebrn** [constanline/XQuickEnergy#286]
### 程序版本 / 框架版本 / 模块版本

支付宝10.5.10.8000，原版XP3.1.5，模块1.1.6

### 系统版本 / Android版本

MIUI9，Android7.1.1

### 详细描述问题发生的具体原因

支付宝新村界面显示摆餐，在模块上没有提示摆餐记录
![Screenshot_2023-08-26-15-09-02-462_com eg android AlipayGphone](https://github.com/constanline/XQuickEnergy/assets/140738041/b512c52d-e7ba-40a0-9421-4c176c91fee8)
![Screenshot_2023-08-26-15-08-27-554_pansong291 xposed quickenergy repair](https://github.com/constanline/XQuickEnergy/assets/140738041/176c859c-8d91-451e-8e8e-af0828efba66)
__

### 提供模块问题 Log 或必要 Log

[runtime.log](https://github.com/constanline/XQuickEnergy/files/12444792/runtime.log)

**Comment by constanline** [comment]
这是bug？？？

**Comment by berebrn** [comment]
> 这是bug？？？

请大佬指教🙏

**Comment by constanline** [comment]
应该算增强吧，今天加上
