### ISSUE TITLE
使用gson代替sdk自带的org.json能否减少一些代码量？

### ISSUE THREAD

**Issue by acooler15** [constanline/XQuickEnergy#287]
### 增强类型

优化型增强

### 具体描述

使用gson代替sdk自带的org.json能否减少一些代码量？

**Comment by constanline** [comment]
首先这种问题请发在讨论区。
然后说下这个问题本身，
1、在本项目中没有使用到json的高级特性，比如与类实例互转，都是基本用法，所以并不能简化代码。
2、我记得xposed注入的时候，并不能带入本身的依赖，也就意味着引入的gson并不能在Hook部分使用。
3、zfb自己用的fastjson，如果确实想在Hook部分使用某些json模块高级功能，可以compileOnly的方式引入fastjson，或者通过hook方式使用
