### ISSUE TITLE
支付宝后台退出后

### ISSUE THREAD

**Issue by xiaoqi2020** [constanline/XQuickEnergy#289]
### 程序版本 / 框架版本 / 模块版本

lspctah

### 系统版本 / Android版本

magic7.0

### 详细描述问题发生的具体原因

现在是和水晶 1.5.5 修复版一起使用
芝麻粒上个版本还挺稳定的，支付宝刚更新了，不知道是不是支付宝的原因！

出现的问题如下
支付宝挂后台不定时自动关闭了，不知道是什么原因。
支付宝退出后，水晶也会退出，状态栏不显示了，但，芝麻粒还会显示在状态栏，显示扫描和运行！

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by xiaoqi2020** [comment]
[runtime.log](https://github.com/constanline/XQuickEnergy/files/12445314/runtime.log)

**Comment by constanline** [comment]
见楼上，不要使用水晶155修复版。这个版本本身是有问题的
