### ISSUE TITLE
建议增加。芝麻信用任务。待办 蚂蚁森林 蚂蚁庄园 蚂蚁新村 芭芭农业

### ISSUE THREAD

**Issue by qq495946172** [constanline/XQuickEnergy#290]
### 增强类型

功能型增强

### 具体描述

建议增加。芝麻信用任务。待办 蚂蚁森林 蚂蚁庄园 蚂蚁新村 芭芭农业

**Comment by cyanide233** [comment]
可以加一个雇佣小鸡产肥功能

**Comment by alinnse** [comment]
添加待办时开启持续做，芝麻粒APP开启森林庄园农场相关功能，再开启收芝麻粒功能，可以自动完成

**Comment by LazyImmortal** [comment]
这个你可以手动开启任务呀，支付宝能自动续接任务的。没必要弄这个功能。

**Comment by kimshift** [comment]
这个功能没必要呀，收到开启一次，支付宝后面都会自动持续做的了。只要芝麻粒完成每日：蚂蚁森林 蚂蚁庄园 蚂蚁新村 芭芭农业的工作就会自动完成待办了。所以没必要

**Comment by constanline** [comment]
楼上已说明
