### ISSUE TITLE
无法收取能量

### ISSUE THREAD

**Issue by cyanide233** [constanline/XQuickEnergy#293]
### 程序版本 / 框架版本 / 模块版本

程序版本 10.5.10 框架版本 LSPosed 1.8.6 模块版本 1.1.6

### 系统版本 / Android版本

氢os  Android 11

### 详细描述问题发生的具体原因

功能开启后无法收取能量，也无法偷取好友能量，能量雨可以使用。
其他功能正常，庄园记录和其他记录都有，森林记录是空的，好友统计也能显示，不知道是什么原因

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by acooler15** [comment]
runtime.log文件呢？还有是否被支付宝限制了？

**Comment by cyanide233** [comment]
rumtime.log怎么导出呀，支付宝没提示过被限制

**Comment by 965973717** [comment]
> RUNTIME.log文件呢？还有是否被支付宝限制了？

#给补充一下。除了普通的能量球不会收取（自己的和好友的）外，其他功能都是可以执行的

> @`
[runtime.log](https://github.com/constanline/XQuickEnergy/files/12450440/runtime.log)
`

**Comment by cyanide233** [comment]
> 

嗯，森林日志那里是空的，其他的功能正

**Comment by constanline** [comment]
#282 
相同的问题，支付宝缺少读写文件的权限。日志里明显能看出，芝麻粒能正确读写配置文件(config)，但是支付宝启动时每次都认为config是空重新获取。

**Comment by cyanide233** [comment]
> #282 相同的问题，支付宝缺少读写文件的权限。日志里明显能看出，芝麻粒能正确读写配置文件(config)，但是支付宝启动时每次都认为config是空重新获取。

找到runtime.log了，更新了给你看下

**Comment by 2010litong** [comment]
> 

经过你的提示，打开支付宝的“文件和文档”权限就可以收取能量了！

**Comment by 2010litong** [comment]
> #282 相同的问题，支付宝缺少读写文件的权限。日志里明显能看出，芝麻粒能正确读写配置文件(config)，但是支付宝启动时每次都认为config是空重新获取。

经过你的提示，打开支付宝的“文件和文档”权限就可以收取能量了！
