### ISSUE TITLE
大家都别光提需求和建议了

### ISSUE THREAD

**Issue by is-xianglei** [constanline/XQuickEnergy#294]
### 增强类型

功能型增强

### 具体描述

大家都别光提需求和建议了，给作者打赏一下吧，这才是支持作者前进的动力啊兄弟们。
打赏多少都是个心意

**Comment by luzilong520** [comment]
赞同

**Comment by TikTokJTT** [comment]
早赞赏过了。
呼吁赞赏开源项目是好，但没必要在这刻意点出来，这里是反馈的地方。有赞赏的意愿的自己就会赞赏，没有这意愿的你刻意点出来他也不会赞赏。

**Comment by Angel-Anderson** [comment]
提需求的时候附上打赏截图，应该更有用😂

**Comment by Zhangfanyu1222** [comment]
> 提需求的时候附上打赏截图，应该更有用😂

up

**Comment by pctit** [comment]
打赏出于自愿，作者大佬肯定也不是靠这个过日子。现在大家都反馈和建议也是种支持和鼓励。目前社区生态还是很和谐的，也不要绑架所有人了，有能力的同学可以请作者喝杯咖啡。

**Comment by berebrn** [comment]
![mmexport1693163411268](https://github.com/constanline/XQuickEnergy/assets/140738041/2bee4ea0-03ff-4017-bfaa-94c188721e16)
![Screenshot_2023-08-28-03-12-35-626_com tencent mm](https://github.com/constanline/XQuickEnergy/assets/140738041/0ba2ca9a-27e0-4566-b55e-e63d4bed76a1)
这样说的话，我上图，虽然不多，还是可以请大佬喝奶茶的

**Comment by constanline** [comment]
谢谢
