### ISSUE TITLE
被强制使用新蛋卡和被强制捐蛋

### ISSUE THREAD

**Issue by Juggernaut1000** [constanline/XQuickEnergy#295]
### 程序版本 / 框架版本 / 模块版本

支付宝Play 10.5.10.8100、Lsposed 1.8.4、芝麻粒 1.1.6

### 系统版本 / Android版本

MIUI13 22.3.2开发版、Android 11

### 详细描述问题发生的具体原因

关闭支付宝后再打开会被强制使用一张新蛋卡，同时被强制捐赠一颗蛋，即使在设置里关闭此功能仍然无效
![1](https://github.com/constanline/XQuickEnergy/assets/73423673/b983b4d7-fc06-4ae4-b52a-164781986f4c)
![2](https://github.com/constanline/XQuickEnergy/assets/73423673/88e7fdf7-6e1a-424d-bbda-3e39a0d1f03b)
![3](https://github.com/constanline/XQuickEnergy/assets/73423673/03f9b749-bfed-4d3b-84d4-215a2e127f5e)
![4](https://github.com/constanline/XQuickEnergy/assets/73423673/d4064b37-f065-4172-976b-e0f8b1569166)

以及日志（forest.log/farm.log）无法显示，重新安装应用和模块也无法显示记录

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by LazyImmortal** [comment]
Play版的权限问题，芝麻粒生成的文件，支付宝读写不了，所以是按照默认配置进行的，又因为写不进去记录，所以每次启动都会执行一次。

**Comment by TikTokJTT** [comment]
> Play版的权限问题，芝麻粒生成的文件，支付宝读写不了，所以是按照默认配置进行的，又因为写不进去记录，所以每次启动都会执行一次。

国区版10.3.80.8800亦有一样的情况

**Comment by LazyImmortal** [comment]
> > Play版的权限问题，芝麻粒生成的文件，支付宝读写不了，所以是按照默认配置进行的，又因为写不进去记录，所以每次启动都会执行一次。
> 
> 国区版10.3.80.8800亦有一样的情况

权限没给到位

**Comment by LazyImmortal** [comment]
https://github.com/constanline/XQuickEnergy/discussions/282#discussion-5556082
