### ISSUE TITLE
支付宝总是提示异常操作

### ISSUE THREAD

**Issue by stupidloud** [constanline/XQuickEnergy#299]
### 程序版本 / 框架版本 / 模块版本

10.5.10.8100  1.16

### 系统版本 / Android版本

miui14

### 详细描述问题发生的具体原因

支付宝经常提示异常操作

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by dsjun007** [comment]
每分钟收取个数少点

**Comment by cls-292** [comment]
建议收取间隔设置成大于100

**Comment by constanline** [comment]
调整下森林检测间隔、收取间隔、限制每分钟收取个数等等

**Comment by constanline** [comment]
另外这种问题请发到讨论区
