### ISSUE TITLE
建议增加启动提示

### ISSUE THREAD

**Issue by xzcgg** [constanline/XQuickEnergy#307]
### 增强类型

强迫症增强

### 具体描述

没有启动提示总感觉少了点啥，建议增加打开支付宝后气泡提示：芝麻粒加载成功

**Comment by dsjun007** [comment]
状态栏会显示图标

**Comment by kimshift** [comment]
加没加在成功看手机状态栏不就得了么，非要弹框才行呀【手动狗头】

**Comment by xzcgg** [comment]
因为强迫症呀

**Comment by xzcgg** [comment]
> 加没加在成功看手机状态栏不就得了么，非要弹框才行呀【手动狗头】

因为强迫症呀
