### ISSUE TITLE
对 #12 这条issue挖个坟，再深入请教“constanline”大

### ISSUE THREAD

**Issue by P3R5T7U9** [constanline/XQuickEnergy#31]
抱歉打扰“constanline”大了，对 #12 这条issue再挖个坟进一步问下；

我是近两天才知道“芝麻粒”这个xp模块，最初也是用此issue中层主发的shell命令来启动zfb调用模块(小声：因为我在用这个模块之前，其它一些收能量的模块用相同的shell命令都可以调起且可以收能量)，一看根本没效果，本想开个issue反馈下，但刚看到四天前已有层主反馈过了，随后见“constanline”大你回复这个模块不是注入到“com.alipay.android.launcher.service.LauncherService"这个最常用的service里。。。

那麻烦“constanline”大再回复甩调起此模块并可以收能量的“全新”shell命令呗。。。之前翻了下此模块的源码，很多地方由于没注释看⑧懂，一直没找到此模块注入是哪个新servcie😭
(小声：由于我是重度的shell爱好者，弱弱求“constanline”大满足下我这个“特殊癖好”惹；亦或者“constanline”大你在开发此模块时并未考虑用shell来调起，并未预设用来调起的service，那就算了😖)

**Comment by constanline** [comment]
10.3版本开始“com.alipay.android.launcher.service.LauncherService“已经不再使用，我猜这也是秋风失效的原因。本插件依托于“com.alipay.dexaop.power.RuntimePowerService”服务
