### ISSUE TITLE
希望加一个大小号，添加当前账号为大号模式

### ISSUE THREAD

**Issue by Aitanquercus** [constanline/XQuickEnergy#310]
### 增强类型

功能型增强

### 具体描述

希望加一个大小号，默认是小号模式，添加当前账号为大号模式，小号模式不检测能量就可以了

**Comment by Zhangfanyu1222** [comment]
![图片](https://github.com/constanline/XQuickEnergy/assets/65014915/d078fcfa-ee50-4982-a0a9-a106afc5f36c)

**Comment by Zhangfanyu1222** [comment]
![图片](https://github.com/constanline/XQuickEnergy/assets/65014915/0a70b721-81b1-42f3-bce2-24a0b6677594) in https://github.com/constanline/XQuickEnergy/discussions/281_

**Comment by hua-sky** [comment]
双开吧。我就是这样的，用着也行。

**Comment by 7L787** [comment]
单机单个，不行就试试双开嘛

**Comment by Aitanquercus** [comment]
> 双开吧。我就是这样的，用着也行。

但是有很多人的需求，就是需要切换登录好几个支付宝账号

**Comment by LazyImmortal** [comment]
> > 双开吧。我就是这样的，用着也行。
> 
> 但是有很多人的需求，就是需要切换登录好几个支付宝账号

那他们现在该使用的就不是芝麻粒而是其他

**Comment by Aitanquercus** [comment]
> > > 双开吧。我就是这样的，用着也行。
> > 
> > 
> > 但是有很多人的需求，就是需要切换登录好几个支付宝账号
> 
> 那他们现在该使用的就不是芝麻粒而是其他

有大小号之后，其他的，比如水晶，就可以歇歇了

**Comment by hua-sky** [comment]
> > 双开吧。我就是这样的，用着也行。
> 
> 但是有很多人的需求，就是需要切换登录好几个支付宝账号

双开的配合xposed edge pro全自动运行，自动切换账号

**Comment by pctit** [comment]
用两台手机，一台专挂小号就行了

**Comment by Aitanquercus** [comment]
> 用两台手机，一台专挂小号就行了

再买一台手机，专门挂小号？
