### ISSUE TITLE
偶尔强制跳转到支付宝界面

### ISSUE THREAD

**Issue by kimshift** [constanline/XQuickEnergy#313]
### 增强类型

功能型增强

### 具体描述

支付宝版本：10.5.10  lspatch内置-芝麻粒版本1.1.7 
问题：继1.1.6之后发现每天偶尔会强制跳转至支付宝界面不知道是什么原因

**Comment by LazyImmortal** [comment]
这种问题你应该发评论区吧？
![Screenshot_2023-08-31-18-09-20-155_pansong291.xposed.quickenergy.repair.png](https://github.com/constanline/XQuickEnergy/assets/44522979/9d943c3b-2a22-4e03-acd5-4de16cb12cf6)
基础设置里：保活目标改为Service，关闭“超时时重启Activity”

**Comment by TikTokJTT** [comment]
> 这种问题你应该发评论区吧？
> ![Screenshot_2023-08-31-18-09-20-155_pansong291.xposed.quickenergy.repair.png](https://github.com/constanline/XQuickEnergy/assets/44522979/9d943c3b-2a22-4e03-acd5-4de16cb12cf6)
> 基础设置里：保活目标改为Service，关闭“超时时重启Activity”

人家以为这是Bug所以发来这里啊，他要是有你这么懂评论区都不用发了，要不以后发评论区还是发这里先跟你咨询一下，好吗，懂哥！！！

**Comment by LazyImmortal** [comment]
> > 这种问题你应该发评论区吧？
> > ![Screenshot_2023-08-31-18-09-20-155_pansong291.xposed.quickenergy.repair.png](https://user-images.githubusercontent.com/44522979/264612708-9d943c3b-2a22-4e03-acd5-4de16cb12cf6.png)
> > 基础设置里：保活目标改为Service，关闭“超时时重启Activity”
> 
> 人家以为这是Bug所以发来这里啊，他要是有你这么懂评论区都不用发了，要不以后发讨论区还是发这里先跟你咨询一下，好吗，懂哥！！！

你是吃屎了吗？我只是说一下这种问题应该发评论区，又没有不解答。问题反馈发bug，功能提议发enhancement，其他发讨论区。这次说一下，起码他以后就知道了。你在这里发什么癫？

**Comment by TikTokJTT** [comment]
> > > 这种问题你应该发评论区吧？
> > > ![Screenshot_2023-08-31-18-09-20-155_pansong291.xposed.quickenergy.repair.png](https://user-images.githubusercontent.com/44522979/264612708-9d943c3b-2a22-4e03-acd5-4de16cb12cf6.png)
> > > 基础设置里：保活目标改为Service，关闭“超时时重启Activity”
> > 
> > 人家以为这是Bug所以发来这里啊，他要是有你这么懂评论区都不用发了，要不以后发讨论区还是发这里先跟你咨询一下，好吗，懂哥！！！
> 
> 你是吃屎了吗？我只是说一下这种问题应该发评论区，又没有不解答。问题反馈发bug，功能提议发enhancement，其他发讨论区。这次说一下，起码他以后就知道了。你在这里发什么癫？

哟哟哟，这就破防了？《这种问题你应该发评论区吧？》你不会自己说的都不理解吧？？？

**Comment by kimshift** [comment]
> 这种问题你应该发评论区吧？ ![Screenshot_2023-08-31-18-09-20-155_pansong291.xposed.quickenergy.repair.png](https://user-images.githubusercontent.com/44522979/264612708-9d943c3b-2a22-4e03-acd5-4de16cb12cf6.png) 基础设置里：保活目标改为Service，关闭“超时时重启Activity”

好的，收到。谢谢
