### ISSUE TITLE
活力兑换双击卡次数限制出错

### ISSUE THREAD

**Issue by j4Uq** [constanline/XQuickEnergy#321]
### 程序版本 / 框架版本 / 模块版本

1.1.8fix1

### 系统版本 / Android版本

13

### 详细描述问题发生的具体原因

更新新版后才出现的，限制6次兑换双击卡，凌晨已经领过了，结果9点又领了一轮
![Screenshot_20230902-103827_芝麻粒](https://github.com/constanline/XQuickEnergy/assets/6436073/2084873a-4aa7-422c-8187-29b94b037713)
![Screenshot_20230902-103831_芝麻粒](https://github.com/constanline/XQuickEnergy/assets/6436073/93802559-6490-48e6-863b-5f7881863370)

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by constanline** [comment]
#282 疑似权限问题，可以查看statistics文件记录是否正常。如果不正常，请删掉该文件，先开支付宝。

**Comment by ritaferni** [comment]
我也是。今天兑换了3次，v1.1.7。之前的1.1.6也是如此~盼解决

**Comment by constanline** [comment]
删掉statistics，然后别启动芝麻粒，直接启动支付宝(这时会再次执行一次兑换)，观察之后是否依然出现同样的情况。

**Comment by constanline** [comment]
按上面的办法是否有改善？无反馈的话关闭了
