### ISSUE TITLE
新村新增助力功能

### ISSUE THREAD

**Issue by shou-jj** [constanline/XQuickEnergy#322]
### 增强类型

优化型增强

### 具体描述

蚂蚁新村能否增加助力功能，增加邀请摆摊功能。
同时打开了新村捐赠开关，有捐赠行为但是log日志没有记录，建议完善

**Comment by Aitanquercus** [comment]
这个很不错，蚂蚁新村增加邀请好友助力列表

**Comment by ebuluo816** [comment]
附议，邀请摆摊~

**Comment by shou-jj** [comment]
1.2.0新增了新村助力，不过没开关也不能指定助力
