### ISSUE TITLE
支付宝强制关闭两次，第二次芝麻粒才收能量

### ISSUE THREAD

**Issue by dsjun007** [constanline/XQuickEnergy#324]
### 程序版本 / 框架版本 / 模块版本

Magisk26.1 + LSPosed1.9.1

### 系统版本 / Android版本

MIUI14 Android13

### 详细描述问题发生的具体原因

系统： MIUI14 Android13
方式： Magisk26.1 + LSPosed1.9.1
版本： 支付宝10.5.10 8000 + 芝麻粒v1.1.8
问题： 后台运行长时间未工作，支付宝必须强制关闭两次，第一次开支付宝芝麻粒不运行，第二次加载芝麻粒后才生效收能量

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by Aitanquercus** [comment]
> 

长时间不打开支付宝，支付宝掉后台了

**Comment by dsjun007** [comment]
> > 
> 
> 长时间不打开支付宝，支付宝掉后台了

比如今早，第一次打开，都是强制关闭了才打开的，不存在掉后台

**Comment by TikTokJTT** [comment]
> > > 
> > 
> > 长时间不打开支付宝，支付宝掉后台了
> 
> 比如今早，第一次打开，都是强制关闭了才打开的，不存在掉后台

这不就是掉后台的情况吗，装个水晶1.55吧，不用水晶的功能的话就当水晶是个保活插件就好。

**Comment by Aitanquercus** [comment]
> > > 
> > 
> > 
> > 长时间不打开支付宝，支付宝掉后台了
> 
> 比如今早，第一次打开，都是强制关闭了才打开的，不存在掉后台

可以用edge，定时打开支付宝，来解决支付宝掉后台，通知栏不掉，但是插件不工作，这就是支付宝掉后台了

**Comment by constanline** [comment]
> 
> 比如今早，第一次打开，都是强制关闭了才打开的，不存在掉后台

第一开启之后多等一会儿试试看。芝麻粒每次循环执行的操作是一样的，不该出现第一次不工作，第二次反倒工作的情况，所以可能是正在重置statistics。

**Comment by constanline** [comment]
按上面的办法是否有改善？无反馈的话关闭了
