### ISSUE TITLE
miui14自动任务定时打开支付宝插件不运行

### ISSUE THREAD

**Issue by ANANANNN** [constanline/XQuickEnergy#335]
### 程序版本 / 框架版本 / 模块版本

支付宝10.5.16.8100  LSPosed1.9.1 芝麻粒1.1.8

### 系统版本 / Android版本

miui，13

### 详细描述问题发生的具体原因

原来设置定时任务，自动早晨7点打开支付宝，插件随之运行，自动收取能量等。
目前自动打开支付宝不收取能量。

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by dsjun007** [comment]
你的是不是也要强制关闭支付宝以后再开才行，芝麻粒在后台挂着，通知栏也显示，就是过一会儿了就没工作了

**Comment by gaoyuoppa** [comment]
俺也一样，目前我用第三方软件，每一小时，关闭支FB。然后重新打开。

**Comment by Aitanquercus** [comment]
> ### 程序版本 / 框架版本 / 模块版本
> 支付宝10.5.16.8100 LSPosed1.9.1 芝麻粒1.1.8
> 
> ### 系统版本 / Android版本
> miui，13
> 
> ### 详细描述问题发生的具体原因
> 原来设置定时任务，自动早晨7点打开支付宝，插件随之运行，自动收取能量等。 目前自动打开支付宝不收取能量。
> 
> ### 提供模块问题 Log 或必要 Log
> 展开查看

你使用第三方工具，自动打开支付宝之前，需要先强行停止一下支付宝，可以在前一天晚上，先强行停止一下支付宝

**Comment by xiemobiao** [comment]
俺也是一样的miui14,过一会就不运行了

**Comment by xiemobiao** [comment]
俺也是一样的情况，miui14,过一会就不运行了，必须强制结束支付宝进程重新打开

**Comment by TikTokJTT** [comment]
> 我的miui后台也是一会儿就没工作了，不过看别人都可以保活很不解

需要在某个时间段启动的可以用xposed edge pro  
如果想24小时保活的配合水晶1.55r使用，目前有些功能开始可以和芝麻粒互补的，就算你不用水晶里面的功能，但你可以把水晶当做一个保活插件啊

**Comment by xiemobiao** [comment]
> > 我的miui后台也是一会儿就没工作了，不过看别人都可以保活很不解
> 
> 需要在某个时间段启动的可以用xposed edge pro 如果想24小时保活的配合水晶1.55r使用，目前有些功能开始可以和芝麻粒互补的，就算你不用水晶里面的功能，但你可以把水晶当做一个保活插件啊

好的，非常感谢

**Comment by ANANANNN** [comment]
> 同miui14未发现此问题 可以配合水晶155或者语音到账提醒保活

今天早上我试了一下，设置自动任务，早上7点手机管家自动打开支付宝，水晶1.5.5随之运行，芝麻粒没有运行，早上8点我醒来后手动关闭支付宝再打开，芝麻粒运行。
![IMG_20230907_225606](https://github.com/constanline/XQuickEnergy/assets/60524452/0090ec7b-b68f-4ee9-9dde-a5967e409140)
![Uploading Screenshot_2023-09-07-22-55-13-729_pansong291.xposed.quickenergy.repair.jpg…]()

**Comment by ANANANNN** [comment]
![Uploading Screenshot_2023-09-07-22-55-13-729_pansong291.xposed.quickenergy.repair.jpg…]()

**Comment by ANANANNN** [comment]
> > 同miui14未发现此问题 可以配合水晶155或者语音到账提醒保活
> 
> 今天早上我试了一下，设置自动任务，早上7点手机管家自动打开支付宝，水晶1.5.5随之运行，芝麻粒没有运行，早上8点我醒来后手动关闭支付宝再打开，芝麻粒运行。 ![IMG_20230907_225606](https://user-images.githubusercontent.com/60524452/266357499-0090ec7b-b68f-4ee9-9dde-a5967e409140.jpg)

![Uploading IMG_20230907_230022.jpg…]()

**Comment by Aitanquercus** [comment]
> > 同miui14未发现此问题 可以配合水晶155或者语音到账提醒保活
> 
> 今天早上我试了一下，设置自动任务，早上7点手机管家自动打开支付宝，水晶1.5.5随之运行，芝麻粒没有运行，早上8点我醒来后手动关闭支付宝再打开，芝麻粒运行。 ![IMG_20230907_225606](https://user-images.githubusercontent.com/60524452/266357499-0090ec7b-b68f-4ee9-9dde-a5967e409140.jpg)

早上六点五十几分，手动强行停止一下支付宝，然后打开支付宝，让支付宝前台弹出页面，手机不要息屏，就不会有支付宝掉后台的问题

**Comment by Aitanquercus** [comment]
> > > > 同miui14未发现此问题 可以配合水晶155或者语音到账提醒保活
> > > 
> > > 
> > > 今天早上我试了一下，设置自动任务，早上7点手机管家自动打开支付宝，水晶1.5.5随之运行，芝麻粒没有运行，早上8点我醒来后手动关闭支付宝再打开，芝麻粒运行。 ![IMG_20230907_225606](https://user-images.githubusercontent.com/60524452/266357499-0090ec7b-b68f-4ee9-9dde-a5967e409140.jpg)
> > 
> > 
> > 早上六点五十几分，手动强行停止一下支付宝，然后打开支付宝，让支付宝前台弹出页面，手机不要息屏，就不会有支付宝掉后台的问题
> 
> 开自动任务就是因为在睡觉没醒啊。。

定个闹钟，把自己弄醒，弄好开始偷能量之后，再回去睡个回笼觉

**Comment by ANANANNN** [comment]
搭配水晶后正常。

**Comment by constanline** [comment]
> 搭配水晶后正常。

要注意不要使用“水晶155修复版”会导致后台崩溃，可以使用水晶155。

**Comment by ANANANNN** [comment]
> > 搭配水晶后正常。
> 
> 要注意不要使用“水晶155修复版”会导致后台崩溃，可以使用水晶155。

好的
