### ISSUE TITLE
复活好友能量bug

### ISSUE THREAD

**Issue by luozongkai** [constanline/XQuickEnergy#345]
### 程序版本 / 框架版本 / 模块版本

版本：10.5.16.8500 ，1.8.6 (6932) - Zygisk，版本：1.1.9

### 系统版本 / Android版本

miui Android13

### 详细描述问题发生的具体原因

复活好友能量这功能没开，但还是复活好友能量了。

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by constanline** [comment]
发日志看看

**Comment by dsjun007** [comment]
> 有没有带着水晶一起用 ~_~？

单用芝麻粒，之前水晶不掉后台不担心能量球被摸

**Comment by luozongkai** [comment]
> 有没有带着水晶一起用 ~_~？

没，只用芝麻粒，用新版本暂时没问题了。
