### ISSUE TITLE
没有日志写入

### ISSUE THREAD

**Issue by talksilence** [constanline/XQuickEnergy#351]
### 程序版本 / 框架版本 / 模块版本

支付宝谷歌10.5.16.8500，lsp1.9.1,magisk delta26301

### 系统版本 / Android版本

MIUI14 A13

### 详细描述问题发生的具体原因

总日志里有记录，但是farm和other日志里没有记录
![Screenshot_2023-09-09-10-53-40-989_bin mt plus](https://github.com/constanline/XQuickEnergy/assets/59134293/ac25c837-fafb-46a2-90b6-32faa78c0447)
![Screenshot_2023-09-09-10-55-09-054_bin mt plus](https://github.com/constanline/XQuickEnergy/assets/59134293/d4f0a730-12b1-4c42-8d4c-590b7669d412)

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by dsjun007** [comment]
该给的权限都给上

**Comment by talksilence** [comment]
> 该给的权限都给上

权限都给了，之前使用都是正常的，在fram日志里有记录。但是今天卸载重装后就都没有日志记录了

**Comment by talksilence** [comment]
问题解决了，是因为存储空间隔离不知道出了什么问题，导致支付宝自己的download目录和根目录的download目录没完全同步过来。把两个download目录删掉，存储空间隔离里重新设置一下就能解决了
