### ISSUE TITLE
步数未设置会自动修改

### ISSUE THREAD

**Issue by Norman45** [constanline/XQuickEnergy#357]
### 程序版本 / 框架版本 / 模块版本

1.2.0+vmos

### 系统版本 / Android版本

7.0

### 详细描述问题发生的具体原因

我设置自定义步数为0，结果0点同步了36440步，应该不同步才对，这是不是bug了

### 提供模块问题 Log 或必要 Log

00:35:45 绿色经营📊签到成功
00:35:46 捐出活动❤️[36440步]#兑换0.62元公益金
00:35:47 绿色经营📊签到成功
00:35:47 完成任务🧾[每日步数500步]
00:35:47 完成任务🧾[逛一逛文体线上跑]
00:35:47 完成任务🧾[参与NBA抽奖1次]
00:35:48 完成任务🧾[参与走城市经典路线]
00:35:48 完成任务🧾[去爱动浏览健身课程15秒]
00:35:48 绿色经营📊任务完成
00:35:48 完成任务🧾[逛一逛蚂蚁森林]
配置
    "minExchangeCount": 18000,
    "latestExchangeTime": 10,
    "syncStepCount": 0,

**Comment by LazyImmortal** [comment]
芝麻粒的同步步数时间不是在0点，而且你的日志里写的也不是同步步数。应该是你在其他什么渠道把步数给改了，然后这个步数大于了minExchangeCount，所以芝麻粒自动给你捐步数了。就这看下来，一切正常，芝麻粒完全没出问题啊。

**Comment by constanline** [comment]
首先芝麻粒在6点之后才可能会同步步数，其次同步步数范围在设置值与设置值+2000之间波动(如果设置值>0的话)。所以请检查是否有其他模块在运行
