### ISSUE TITLE
双开之后配置（log）文件保存路径问题

### ISSUE THREAD

**Issue by SpringManer** [constanline/XQuickEnergy#364]
### 程序版本 / 框架版本 / 模块版本

芝麻粒：1.2.0，LSPosed:1.9.1

### 系统版本 / Android版本

miui14

### 详细描述问题发生的具体原因

用LSPosed的XSpace功能双开的芝麻粒（系统双开的支付宝），会发现配置文件保存不了，观察了下是路径读取的问题。

针对此类双开的情况，配置文件的存储/读取路径会访问异常，是不是代码路径是写死的，可以改成相对路径 。

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

用LSPosed的XSpace功能双开的芝麻粒（系统双开的支付宝），会发现配置文件保存不了，观察了下是路径读取的问题。

针对此类双开的情况，配置文件的存储/读取路径会访问异常，是不是代码路径是写死的，可以改成相对路径 。

</code></pre></details>

**Comment by dsjun007** [comment]
芝麻粒也用系统双开

**Comment by SpringManer** [comment]
测试了一下，好像是确实可以了 。赞

**Comment by xin877851977** [comment]
> 芝麻粒也用系统双开

我芝麻粒双开了，但是呢好友列表获取不了，只有个“我”在那
