### ISSUE TITLE
无法记录log和好友列表，文件权限有问题

### ISSUE THREAD

**Issue by Albert-D** [constanline/XQuickEnergy#37]
手机是基于Android13的MIUI14，
支付宝app是play最新版的10.3.80.9100

问题表现：
已经给予了文件的读取权限，可以正常生成xqe文件夹，可以保存config.json的配置数据，但是无法保存各种log，log文件都是0kb，而且无法保存好友列表和合种列表

部分runningtime.log截图如下：
![Screenshot_2023-07-24-10-25-21-093_bin mt plus](https://github.com/constanline/XQuickEnergy/assets/22720162/c24ec637-b1ca-4772-a6e4-514a107d6503)

**Comment by constanline** [comment]
这是zfb缺少访问文件权限。play版zfb的api版本可能29以上，如果是，需要单独赋予访问非app目录的权限。

**Comment by Albert-D** [comment]
> config能输出，说明插件本身的读写权限没问题。你遇到的问题是zfb缺少访问文件权限。play版zfb的api版本可能29以上，如果是，需要单独赋予访问非app目录的权限。

请问是要给予zfb访问非app目录的权限吗？好像这个权限很不好给，有没有操作建议呀？我Google了一下还是不知道怎么操作。

**Comment by constanline** [comment]
> 

api30以上我记得有一个跟干净，上面只有一个开关选项的赋权窗口，专门用于赋予读写所有文件夹的权限

**Comment by constanline** [comment]
1.0.14已调整为存储到Download目录下，看下目前是否正常

**Comment by constanline** [comment]
无反馈，关闭issue
