### ISSUE TITLE
建议更改配置文件存储路径

### ISSUE THREAD

**Issue by Rex-Yeung** [constanline/XQuickEnergy#38]
建议将配置文件的存储路径更改到Documents或者是Download等标准文件夹下，这样Target在30以上的支付宝也能够使用。

**Comment by Zhangfanyu1222** [comment]
存储空间隔离就行

**Comment by Rex-Yeung** [comment]
> 存储空间隔离就行

不是每个人都用存储空间隔离这个应用的

**Comment by Albert-D** [comment]
> > 存储空间隔离就行
> 
> 不是每个人都用存储空间隔离这个应用的

是的，我被迫放弃play版，改用国内版本的zfb了😭

**Comment by constanline** [comment]
> 建议将配置文件的存储路径更改到Documents或者是Download等标准文件夹下，这样Target在30以上的支付宝也能够使用。

昨天已经加入计划了

**Comment by constanline** [comment]
1.0.14已调整

**Comment by mapleshadow** [comment]
play版可以使用，具体是：取消芝麻粒的存储隔离（芝麻粒符合安卓标准不需要隔离），隔离支付宝，给支付宝访问Download的权限，搞定。
