### ISSUE TITLE
可以添加农场施肥和蚂蚁新村的领币嘛

### ISSUE THREAD

**Issue by canyu1111** [constanline/XQuickEnergy#39]
可以添加农场施肥和蚂蚁新村的领币嘛？然后运动自动行走也加入就好了🥰

**Comment by constanline** [comment]
农场施肥需要生成wua，会比较麻烦，暂不考虑。
蚂蚁新村领币之后会加。
自动行走没了解过，看情况吧。
另外昨天投票结果是专精森林，所以这些短期内可能都不会实现。

**Comment by sundongxiao** [comment]
希望增加农场施肥功能默认不运行，可以自定义次数后运行

**Comment by usleolihao** [comment]
刚接触插件开发，想加入开发蚂蚁新村部分，鼓起勇气想问问大佬能不能带带我，请求指点。

**Comment by constanline** [comment]
已完成
