### ISSUE TITLE
通知栏锁不住

### ISSUE THREAD

**Issue by HuiNIMA** [constanline/XQuickEnergy#4]
开启后支付宝图标上一直有角标，而且通知栏容易被一键清理误清理掉

**Comment by constanline** [comment]
请说明插件版本、系统版本、使用方式等信息。目前除此以外没收到通知栏会被清理的反馈。

**Comment by EatmeIon** [comment]
> 请说明插件版本、系统版本、使用方式等信息。目前除此以外没收到通知栏会被清理的反馈。

·这个模块绑定的是那个服务，比如我要使用乖巧模式，需要把哪个进程加入白名单？

**Comment by constanline** [comment]
> > 请说明插件版本、系统版本、使用方式等信息。目前除此以外没收到通知栏会被清理的反馈。
> 
> ·这个模块绑定的是那个服务，比如我要使用乖巧模式，需要把哪个进程加入白名单？

com.alipay.dexaop.power.RuntimePowerService

**Comment by HuiNIMA** [comment]
插件版本：1.0.0-beta8
系统版本：MIUI 14 V14.23.7.10.DEV（Android 13）
使用方式：lsposed 1.8.6(6951)-Zygisk
使用水晶1.5.5-release及之前的版本不会发生这种情况

**Comment by constanline** [comment]
> 插件版本：1.0.0-beta8 系统版本：MIUI 14 V14.23.7.10.DEV（Android 13） 使用方式：lsposed 1.8.6(6951)-Zygisk 使用水晶1.5.5-release及之前的版本不会发生这种情况

同MIUI14(Android13)+LSPosed1.8.6环境未发现此问题，是否与其他插件一同使用？其他插件的森林配置是怎么样的

**Comment by HuiNIMA** [comment]
与水晶一起使用，配置都一样，支付宝设置里的通知管理也一样
![IMG_20230715_231439](https://github.com/constanline/XQuickEnergy/assets/33143156/ae6ce912-85d5-4273-8902-e2f3e94fbcc4)

![IMG_20230715_231223](https://github.com/constanline/XQuickEnergy/assets/33143156/492364ea-f150-4a9a-97c9-cfdb4c812a6f)

**Comment by HuiNIMA** [comment]
经排查是与水晶产生冲突，停用水晶后正常，希望大佬早日完善插件，这样就可以彻底卸载水晶了

**Comment by constanline** [comment]
> 与水晶一起使用，配置都一样，支付宝设置里的通知管理也一样 ![IMG_20230715_231439](https://user-images.githubusercontent.com/33143156/253748859-ae6ce912-85d5-4273-8902-e2f3e94fbcc4.jpg)
> 
> ![IMG_20230715_231223](https://user-images.githubusercontent.com/33143156/253748777-492364ea-f150-4a9a-97c9-cfdb4c812a6f.jpg)

下个版本我会修改频道ID来尝试避免与其他插件在通知栏上出现冲突
