### ISSUE TITLE
召回小鸡功能失效

### ISSUE THREAD

**Issue by NianBroken** [constanline/XQuickEnergy#411]
### 程序版本 / 框架版本 / 模块版本

支付宝：10.5.33.8000、LSPosed：1.6.5、Zygisk - LSPosed：v1.9.2 (7024)、芝麻粒：1.2.0

### 系统版本 / Android版本

Android 13

### 详细描述问题发生的具体原因

null

### 提供模块问题 Log 或必要 Log

null

**Comment by constanline** [comment]
#389
