### ISSUE TITLE
1.0.9小米报毒a.gray.GmPluginTools

### ISSUE THREAD

**Issue by chan1108** [constanline/XQuickEnergy#42]
![Screenshot_2023-07-28-00-13-02-346_com miui packageinstaller](https://github.com/constanline/XQuickEnergy/assets/54262303/74d23507-59b8-40d7-b36c-fe4ad739e0e0)

**Comment by Zhangfanyu1222** [comment]
右上角设置，把病毒检测关闭就好了

**Comment by constanline** [comment]
厂家报毒不是我能控制的。不过为了个人的金融及信息安全，如果想对本APP进行学习研究，请自行拉取代码编译。
