### ISSUE TITLE
澎湃os上的使用异常

### ISSUE THREAD

**Issue by lswlc33** [constanline/XQuickEnergy#420]
### 程序版本 / 框架版本 / 模块版本

模块1.2.0 lsp1.9.2 支付宝10.5.30.9100

### 系统版本 / Android版本

澎湃OS 安卓14

### 详细描述问题发生的具体原因

修改设置选项返回能保存，但是没有实际生效，模块仅会默认运行初始勾选的几个选项，同时无法读取联系人列表

目测应该是无法读取配置文件，按照初始选项进行操作

具体看lsp日志

### 提供模块问题 Log 或必要 Log

[LSPosed_2023-11-15T18_48_42.503008.zip](https://github.com/constanline/XQuickEnergy/files/13363517/LSPosed_2023-11-15T18_48_42.503008.zip)

**Comment by buddingworld** [comment]
是不是没给支付宝读写文件权限呐

**Comment by lswlc33** [comment]
> 是不是没给支付宝读写文件权限呐

神医，关键安装几次支付宝也不问我要权限，我也没注意到
