### ISSUE TITLE
建议增加配置导入导出以解决支付宝sdk api31出现的配置读取问题

### ISSUE THREAD

**Issue by o0HalfLife0o** [constanline/XQuickEnergy#424]
### 增强类型

功能型增强

### 具体描述

最近国内版10.5.50.9500发布，sdk api也提高到31，和play版一样了，但随之而来就是原有配置读取的问题，建议像其他xp模块，增加配置导入导出的功能，以解决无法读取配置文件的问题

**Comment by Zhangfanyu1222** [comment]
其实可以用旧版支付宝，没必要一直更新

**Comment by colin2022** [comment]
请问。如果要用新版本支付宝的话。只要清空数据全部重新配置芝麻粒就行了吗？

**Comment by lee1ei** [comment]
读取配置是个问题，，，每次读取的目录不稳定，有时download下面，有时读写data，而且经常丢失配置，还可能变成默认配置（但实际还能按个人配置运行），希望能优化一下，谢谢

**Comment by constanline** [comment]
> 读取配置是个问题，，，每次读取的目录不稳定，有时download下面，有时读写data，而且经常丢失配置，还可能变成默认配置（但实际还能按个人配置运行），希望能优化一下，谢谢

读取目录不会读data，如果出现请确认是否使用了其他软件。有些系统会在支付宝升级后丢失权限而不是丢失配置，这点是系统和支付宝决定的，模块存取并不会出现你说的问题。

**Comment by constanline** [comment]
权限问题看下 #481
