### ISSUE TITLE
庄园能不能不优先喂那些特殊美食

### ISSUE THREAD

**Issue by zzqxztc** [constanline/XQuickEnergy#425]
### 增强类型

强迫症增强

### 具体描述

个人喜欢堆历次活动收集的美食。
之前没用芝麻粒的庄园。今天开了以后，好家伙，把我活动累积的各种美食一次性喂到饱。。。
可不可以像原版那样只使用饲料喂食，或者设置一个开关。

**Comment by CoolBreezeArcanine** [comment]
同，攒了好久的绝版饲料，几乎在一分钟内被炫完了，哭瞎😭😭😭

**Comment by constanline** [comment]
下个版本新增配置
