### ISSUE TITLE
好友统计里面只显示id数字，不显示备注

### ISSUE THREAD

**Issue by Cgccvhgvhvv** [constanline/XQuickEnergy#426]
### 程序版本 / 框架版本 / 模块版本

LSPosed 1.9.2

### 系统版本 / Android版本

Android 12

### 详细描述问题发生的具体原因

好友统计里面只显示好友的id，不显示备注名称。
![Uploading IMG_20231123_142903.jpg…]()

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by Cgccvhgvhvv** [comment]
![Uploading IMG_20231123_142903.jpg…]()

**Comment by Angel-Anderson** [comment]
删除friendId.list文件，重新打开支付宝等待一会

**Comment by Cgccvhgvhvv** [comment]
> 删除friendId.list文件，重新打开支付宝等待一会

可以了，多谢大佬。我一直用MT打开friendid.list后全选删除，看来那个办法不行，还是删文件彻底。

**Comment by Cgccvhgvhvv** [comment]
close
