### ISSUE TITLE
最新版支付宝似乎部分功能失效

### ISSUE THREAD

**Issue by wyfang** [constanline/XQuickEnergy#428]
### 程序版本 / 框架版本 / 模块版本

LSPosed 1.9.2 模块版本 1.2.0

### 系统版本 / Android版本

HyperOS 1.0.24.0

### 详细描述问题发生的具体原因

森林能量不收取

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

无log

</code></pre></details>

**Comment by mechanic-Q** [comment]
我的也是失效了

**Comment by wyfang** [comment]
> 我的也是失效了

好像是啥API升级31啥的，开发的事情咋也不懂，反正先用上一大版本。不过芝麻粒好久没更新了。

**Comment by GPXIA** [comment]
部分MIUI14或者HyperOS森林能量不收取，这个问题是因为支付宝在上述系统版本中不能申请读写手机储存，MIUI14或者HyperOS对隐私政策更新了，MIUI14系统新增了分区存储隐私保护机制，率先适配的应用可支持对存储访问权限更细化的控制。简单来说，原来的“读写手机存储”权限细化为“访问照片和视频”权限、“访问文件和文档”权限、“访问音频”权限。适配之后的APP适配就只能用自己的一亩三分地了，除非用户授权，不然无法读公共存储。而新适配的支付宝只有没有了访问文件权限，所以森林能量不收取，目前解决办法是退回到支付宝没有适配这个功能以前的版本。可以在豌豆荚下载支付宝历史版本。可以长按支付版桌面图标--应用信息--权限管理，有没有 读写手机储存 这个权限，如果有，打开这个权限 蚂蚁森林可以收能量。

**Comment by wyfang** [comment]
一直用低版本肯定不是长久之计。这么说的话，继续要一个修改app权限的模块。

**Comment by constanline** [comment]
尝试重新授权，#481 看下第一条。最新版本支付宝测试是正常的。
