### ISSUE TITLE
最新版支付宝启动直接卡死

### ISSUE THREAD

**Issue by xusheng1987** [constanline/XQuickEnergy#441]
### 程序版本 / 框架版本 / 模块版本

支付宝10.5.56.9000 LSposed1.9.2 模块1.2.3-beta6

### 系统版本 / Android版本

HyperOS 1.0.3.0  Android 14

### 详细描述问题发生的具体原因

启动直接卡死

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by qoocharly** [comment]
支付宝卡死可以尝试用文件管理器删除download下的xqe文件夹

**Comment by akiziname** [comment]
我也有一样的问题，删除以后也不行

**Comment by qoocharly** [comment]
> 我也有一样的问题，删除以后也不行

估计是bug，试试删除以后在download文件夹里创建useMedia改变一下路径试试

**Comment by Cp0204** [comment]
> 支付宝卡死可以尝试用文件管理器删除download下的xqe文件夹

谢谢，我用这个方法奏效

**Comment by constanline** [comment]
一般来说是无法读取/创建配置导致的。#481 参考这个的第一条
