### ISSUE TITLE
无法使用新路径的xqe

### ISSUE THREAD

**Issue by qinbo1008** [constanline/XQuickEnergy#442]
### 程序版本 / 框架版本 / 模块版本

lsposed 1.9.2

### 系统版本 / Android版本

coloros 14

### 详细描述问题发生的具体原因

即使在download目录下创建了useMedia文件夹，依旧只读取download下的xqe，删除了xqe也依旧会在download下自行重建，而不使用Android/media/com.eg.android.AlipayGphone/目录

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by lee1ei** [comment]
同样情况

**Comment by qinbo1008** [comment]
您的邮件已送达，主淫会尽快恢复滴(>_<)

**Comment by acooler15** [comment]
创建`useMedia`文件呢？

**Comment by qinbo1008** [comment]
> 创建`useMedia`文件呢？

一样无效

**Comment by hhhhhge** [comment]
版本升级了吗

**Comment by qinbo1008** [comment]
> 版本升级了吗

已经是最新的10.5.36.8100

**Comment by kissbzm** [comment]
创建download/useMedia
解决问题
不是download/xqe/useMedia

**Comment by qinbo1008** [comment]
您的邮件已送达，主淫会尽快恢复滴(>_<)

**Comment by constanline** [comment]
#481

**Comment by qinbo1008** [comment]
您的邮件已送达，主淫会尽快恢复滴(>_<)
