### ISSUE TITLE
神奇海洋不自动做任务，神奇物种没有自动抽卡

### ISSUE THREAD

**Issue by wh-990624** [constanline/XQuickEnergy#451]
### 程序版本 / 框架版本 / 模块版本

1.2.3-beta6

### 系统版本 / Android版本

MIUI14 Android 13

### 详细描述问题发生的具体原因

神奇海洋不自动做任务  神奇物种没有抽好友卡  以及能否增加神奇海洋合成万能卡 以及使用万能卡功能？

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by constanline** [comment]
@cwj851 提供的pr https://github.com/constanline/XQuickEnergy/pull/471 似乎包含了这些内容，之前神奇物种卡片也是由这位维护的。确认下新版是否正常。
万能卡会在之后考虑
