### ISSUE TITLE
作者大大您好，支付宝现在新出了木兰币收集活动，需要您增加适配这个功能，如果可以的话请你喝杯咖啡！

### ISSUE THREAD

**Issue by Nice2Boy** [constanline/XQuickEnergy#459]
### 增强类型

功能型增强

### 具体描述

这个活动来自于支付宝蚂蚁新村里的活动，解锁方式之一是通过扣芝麻粒完成任务加信誉分的选项，活动难度很低，就是每天收集一次就行，在技术上也比较容易适配。
![Screenshot_2024-01-19-10-35-35-023_com eg android AlipayGphone-edit](https://github.com/constanline/XQuickEnergy/assets/106030146/c71d0938-3aba-4332-be24-0e4dd924a1cf)
![Screenshot_2024-01-19-10-35-41-609_com eg android AlipayGphone-edit](https://github.com/constanline/XQuickEnergy/assets/106030146/10e1caca-7d65-49bc-932d-4125ddd05253)

**Comment by cwj851** [comment]
这个本身就已经支持了啊

**Comment by Nice2Boy** [comment]
确实有蚂蚁新村这个选项，但是我试了无法收集新村里的“木兰币”，这个可能是个新的活动游戏。

cwj851 ***@***.***> 于 2024年1月19日周五 下午3:02写道：

**Comment by Nice2Boy** [comment]
功能之前就有，是我没有定时开启的原因
