### ISSUE TITLE
听闻QQ群满了，建了个电报群，更安全的交流

### ISSUE THREAD

**Issue by Ja-sagen** [constanline/XQuickEnergy#46]
https://t.me/xqe_zhimali

**Comment by Rex-Yeung** [comment]
你怎么，越俎代庖自己建电报群呀？

**Comment by Ja-sagen** [comment]
> 你怎么，越俎代庖自己建电报群呀？
是我僭越了……

**Comment by Liujishou** [comment]
还是等作者建立吧！你这个不是官方的！

**Comment by WeyLee89** [comment]
> https://t.me/xqe_zhimali

电报要梯子，很多人都没有

**Comment by Zhangfanyu1222** [comment]
怎么敢的（doge

**Comment by cxzrk** [comment]
QQ群解散了，去tg集合也不是不行，至少还有人组建

**Comment by Ja-sagen** [comment]
> > https://t.me/xqe_zhimali
> 
> 电报要梯子，很多人都没有

自然门槛

**Comment by TikTokJTT** [comment]
好家伙，这里是向作者反馈的地方，不是让你来拉皮条的。

**Comment by Rex-Yeung** [comment]
> 好家伙，这里是向作者反馈的地方，不是让你来拉皮条的。作者就是嫌烦才解散了QQ群，你还要来这里搞得乱七八糟的……没当过群主管理是吧！

说得没错，电报群谁不能建？真要建立电报群，也应该是开发者自己来。随便一个人建立一个破群，来代替官方。怎么说都不合理。
