### ISSUE TITLE
自动切换小号功能

### ISSUE THREAD

**Issue by maila888** [constanline/XQuickEnergy#462]
### 增强类型

优化型增强

### 具体描述

下个版本能否增加个自动切换账号号的功能的，加个定时，比如可以自定义30s自动切换下一个账号，这样就可以解放双手了。

**Comment by maila888** [comment]
还有就是一直饱受争议的破5，我感觉可以增加个账号限制，比如不能超过10个账号，这样骨灰级玩家，也可以通过芝麻粒节约更多的时间。比如开了给大号浇水，这样自动切换登录小号的时候，设置间隔30s自动登录下个账号，30s内也能完成浇水和收能量的操作了。

**Comment by colin2022** [comment]
你们能正常编译吗现在。我上个版本能正常编译现在这个版本不行了

**Comment by Liujishou** [comment]
> 你们能正常编译吗现在。我上个版本能正常编译现在这个版本不行了

能啊
