### ISSUE TITLE
/storage/emulated/O/Download/xqe/statistics.json没有与入权限！

### ISSUE THREAD

**Issue by zengerlin** [constanline/XQuickEnergy#465]
### 程序版本 / 框架版本 / 模块版本

支付宝10.5.66/框架版本1.9.2/模块版本v1.2.3-beta6

### 系统版本 / Android版本

Android11

### 详细描述问题发生的具体原因

![storageemulatedODownoadxqestatistics)json没有写入权](https://github.com/constanline/XQuickEnergy/assets/63246108/e179ee5d-ca62-4259-8f5b-98104ea049c4)
![芝麻粒 v1 2 3-beta6【未激活】](https://github.com/constanline/XQuickEnergy/assets/63246108/38f841fd-2496-4e7f-8ebd-4f755b443577)
支付宝的权限里面看不到”始终允许读写手机存储“权限，只有“仅允许访问媒体文件”
以上何解，谢谢！

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by constanline** [comment]
新版本安卓配置高api的程序时，权限模块不一样了，请参考相应系统配置文件存取的方法。
