### ISSUE TITLE
无法执行任何任务

### ISSUE THREAD

**Issue by imRoxy2222** [constanline/XQuickEnergy#477]
### 程序版本 / 框架版本 / 模块版本

芝麻粒版本1.2.3beta12,框架版本lsposed1.9.2(7058)zygisk，支付宝版本10.5. 8000

### 系统版本 / Android版本

系统hyperOS，安卓版本14

### 详细描述问题发生的具体原因

无法执行任何任务，除了每天提交的的2w多步数，支付宝版本从10.3.0一路换到最新版，芝麻粒版本也换过好几个，支付宝以及芝麻粒所有权限都授予了

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

[runtime.txt](https://github.com/constanline/XQuickEnergy/files/14071353/runtime.txt)

**Comment by acooler15** [comment]
估计是文件权限的问题，https://github.com/constanline/XQuickEnergy/releases/tag/v1.2.3-beta6

**Comment by acooler15** [comment]
我的手机小米13，hyperOS，在`Download`下创建了`useMedia`文件夹，所以使用的配置目录在`Android/media`下，目前没有发现文件权限问题，需要注意的是，最好删除原配置，然后直接打开支付宝，让支付宝创建配置。
