### ISSUE TITLE
“立即生效”开关失效

### ISSUE THREAD

**Issue by Zhangfanyu1222** [constanline/XQuickEnergy#487]
### 程序版本 / 框架版本 / 模块版本

LSP1.8.6  1.2.3beta12

### 系统版本 / Android版本

MIUI  A11

### 详细描述问题发生的具体原因

好像beta12版本的“立即生效”开关，在添加了`android:checked="true"`代码后，反而没有效果了。正常来说在修改配置后，到了检测时间会按照新的配置来运行，但是现在要重启支付宝后才能生效了
![图片](https://github.com/constanline/XQuickEnergy/assets/65014915/0b7ef8f4-4ece-4218-908d-984cb862a271)

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by constanline** [comment]
跟这个配置无关，这个是顺手合并的。检查了下，应该是1月20日修改获取好友逻辑的时候把“Config.shouldReload = true;”误删了；下个版本进行修复
![image](https://github.com/constanline/XQuickEnergy/assets/34029504/7f157223-6139-4f22-8d34-96922333129f)

**Comment by constanline** [comment]
跟这个配置无关，这个是顺手合并的。检查了下，应该是1月20日修改获取好友逻辑的时候把“Config.shouldReload = true;”误删了；下个版本进行修复
![image](https://github.com/constanline/XQuickEnergy/assets/34029504/7f157223-6139-4f22-8d34-96922333129f)
