### ISSUE TITLE
一直弹出VPN界面

### ISSUE THREAD

**Issue by Cgccvhgvhvv** [constanline/XQuickEnergy#490]
### 程序版本 / 框架版本 / 模块版本

LSP1.9.2

### 系统版本 / Android版本

12

### 详细描述问题发生的具体原因

突然不停的弹出使用vpn界面，关闭之后一两秒继续弹出，根本关不掉。之前没这个问题，不清楚是哪里出现了问题。

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by Cgccvhgvhvv** [comment]
![Uploading Screenshot_2024-02-04-00-59-41-610_com.eg.android.AlipayGphone.jpg…]()

**Comment by Cgccvhgvhvv** [comment]
![Uploading Screenshot_2024-02-04-00-59-41-610_com.eg.android.AlipayGphone.jpg…]()

**Comment by xin877851977** [comment]
设置里面，把其他-支付宝消费金的功能关掉

**Comment by Cgccvhgvhvv** [comment]
> 设置里面，把其他-支付宝消费金的功能关掉

可以了，多谢

**Comment by Cgccvhgvhvv** [comment]
> 这个功能关了也还是弹

我关了之后就不弹了，重启支付宝了吗
