### ISSUE TITLE
合种浇水不生效，怎么设置都不浇

### ISSUE THREAD

**Issue by Xuliang-Meng** [constanline/XQuickEnergy#51]

**Comment by Rex-Yeung** [comment]
你填错了吧？合种只有一个参数，就是每日浇水克数。

**Comment by Xuliang-Meng** [comment]
> 你填错了吧？合种只有一个参数，就是每日浇水克数。

是只有一个参数  多了也写不进去，我的支部宝版本是10.3.10.8310  不知道是不是版本过低的原因
