### ISSUE TITLE
打开支付宝卡死状态

### ISSUE THREAD

**Issue by xingzaizai** [constanline/XQuickEnergy#514]
### 程序版本 / 框架版本 / 模块版本

LSPosed  1.9.2 芝麻粒：1.2.3-beta14 支付宝：10.5.66.8000

### 系统版本 / Android版本

红米k60 ultra 安卓：14  Hyperos 1.0.7.0

### 详细描述问题发生的具体原因

打开程序直接卡死 无法进入支付宝主界面

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

----part 4 start----
[ 2024-02-20T13:23:02.118        0:   876:  1265 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/verbose_2024-02-20T13:23:02.11791.log
[ 2024-02-20T13:23:05.217        0:   876: 10639 I/LSPosedLogcat   ] !!refresh_modules!!
[ 2024-02-20T13:23:05.218        0:   876:  1265 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/modules_2024-02-20T13:23:05.218554.log
[ 2024-02-20T13:23:34.912     1000:  1793:  5088 I/LSPosed-Bridge  ] [ INFO] 02-20 13:23:34 (PmsHookTarget33) @shouldFilterApplication: query from com.eg.android.AlipayGphone
[ 2024-02-20T13:23:38.106     1000:  1793:  2027 I/LSPosed-Bridge  ] [ INFO] 02-20 13:23:38 (ZygoteArgsHook) @startViaZygote force mount data: 10446 com.eg.android.AlipayGphone
[ 2024-02-20T13:23:38.146    10446: 14942: 14942 I/LSPosed         ] Loading xposed for com.eg.android.AlipayGphone:push/10446
[ 2024-02-20T13:23:38.151    10446: 14942: 14942 I/LSPosed-Bridge  ] Loading legacy module name.caiyao.sporteditor from /data/app/~~iESu9rg69VKYXEfWKPMw6A==/name.caiyao.sporteditor-1eJZgRjze5-xctep041t4w==/base.apk
[ 2024-02-20T13:23:38.161    10446: 14942: 14942 I/LSPosed-Bridge  ]   Loading class name.caiyao.sporteditor.MainHook
[ 2024-02-20T13:23:38.162    10446: 14942: 14942 I/LSPosed-Bridge  ] Loading legacy module pansong291.xposed.quickenergy.repair from /data/app/~~GwjQNEPLWeV_0UH8m6aLuA==/pansong291.xposed.quickenergy.repair-emCpFqFiCqFHFrjefqzQYg==/base.apk
[ 2024-02-20T13:23:38.163    10446: 14942: 14942 I/LSPosed-Bridge  ]   Loading class pansong291.xposed.quickenergy.hook.XposedHook
[ 2024-02-20T13:23:38.528     1000:  1793:  2027 I/LSPosed-Bridge  ] [ INFO] 02-20 13:23:38 (ZygoteArgsHook) @startViaZygote force mount data: 10446 com.eg.android.AlipayGphone
[ 2024-02-20T13:23:38.572    10446: 15030: 15030 I/LSPosed         ] Loading xposed for com.eg.android.AlipayGphone/10446
[ 2024-02-20T13:23:38.576    10446: 15030: 15030 I/LSPosed-Bridge  ] Loading legacy module name.caiyao.sporteditor from /data/app/~~iESu9rg69VKYXEfWKPMw6A==/name.caiyao.sporteditor-1eJZgRjze5-xctep041t4w==/base.apk
[ 2024-02-20T13:23:38.585    10446: 15030: 15030 I/LSPosed-Bridge  ]   Loading class name.caiyao.sporteditor.MainHook
[ 2024-02-20T13:23:38.585    10446: 15030: 15030 I/LSPosed-Bridge  ] Loading legacy module pansong291.xposed.quickenergy.repair from /data/app/~~GwjQNEPLWeV_0UH8m6aLuA==/pansong291.xposed.quickenergy.repair-emCpFqFiCqFHFrjefqzQYg==/base.apk
[ 2024-02-20T13:23:38.587    10446: 15030: 15030 I/LSPosed-Bridge  ]   Loading class pansong291.xposed.quickenergy.hook.XposedHook
[ 2024-02-20T13:23:38.606     1000:  1793:  2027 I/LSPosed-Bridge  ] [ INFO] 02-20 13:23:38 (ZygoteArgsHook) @startViaZygote force mount data: 10446 com.eg.android.AlipayGphone
[ 2024-02-20T13:23:38.659    10446: 15068: 15068 I/LSPosed         ] Loading xposed for com.eg.android.AlipayGphone:lite1/10446
[ 2024-02-20T13:23:38.663    10446: 15068: 15068 I/LSPosed-Bridge  ] Loading legacy module name.caiyao.sporteditor from /data/app/~~iESu9rg69VKYXEfWKPMw6A==/name.caiyao.sporteditor-1eJZgRjze5-xctep041t4w==/base.apk
[ 2024-02-20T13:23:38.688    10446: 15068: 15068 I/LSPosed-Bridge  ]   Loading class name.caiyao.sporteditor.MainHook
[ 2024-02-20T13:23:38.689    10446: 15068: 15068 I/LSPosed-Bridge  ] Loading legacy module pansong291.xposed.quickenergy.repair from /data/app/~~GwjQNEPLWeV_0UH8m6aLuA==/pansong291.xposed.quickenergy.repair-emCpFqFiCqFHFrjefqzQYg==/base.apk
[ 2024-02-20T13:23:38.690    10446: 15068: 15068 I/LSPosed-Bridge  ]   Loading class pansong291.xposed.quickenergy.hook.XposedHook
[ 2024-02-20T13:23:38.719    10450: 15082: 15082 I/LSPosed         ] Loading xposed for pansong291.xposed.quickenergy.repair/10450
[ 2024-02-20T13:23:38.723    10450: 15082: 15082 I/LSPosed-Bridge  ] Loading legacy module pansong291.xposed.quickenergy.repair from /data/app/~~GwjQNEPLWeV_0UH8m6aLuA==/pansong291.xposed.quickenergy.repair-emCpFqFiCqFHFrjefqzQYg==/base.apk
[ 2024-02-20T13:23:38.725    10450: 15082: 15082 I/LSPosed-Bridge  ]   Loading class pansong291.xposed.quickenergy.hook.XposedHook
[ 2024-02-20T13:23:53.032     2000: 15576: 15576 I/LSPosed         ] Loaded manager, skipping next steps
[ 2024-02-20T13:23:55.693        0:   876:  1078 I/lspd            ] This is sticky GC, maxfree is 33554432 minfree is 8388608
[ 2024-02-20T13:23:55.708        0:   876: 14522 W/BpBinder        ] Large or Failed outgoing transaction of 136 bytes, interface descriptor , code 3
[ 2024-02-20T13:23:55.708        0:   876: 14522 E/JavaBinder      ] !!! FAILED BINDER TRANSACTION !!!  (parcel size = 136)
[ 2024-02-20T13:23:55.727        0:   876:  1078 I/lspd            ] This is sticky GC, maxfree is 33554432 minfree is 8388608
[ 2024-02-20T13:23:55.729        0:   876: 14523 W/BpBinder        ] Large or Failed outgoing transaction of 152 bytes, interface descriptor , code 3
[ 2024-02-20T13:23:55.729        0:   876: 14523 E/JavaBinder      ] !!! FAILED BINDER TRANSACTION !!!  (parcel size = 152)
[ 2024-02-20T13:23:55.733        0:   876: 28563 W/BpBinder        ] Large or Failed outgoing transaction of 144 bytes, interface descriptor , code 3
[ 2024-02-20T13:23:55.733        0:   876: 28563 E/JavaBinder      ] !!! FAILED BINDER TRANSACTION !!!  (parcel size = 144)
[ 2024-02-20T13:23:55.737        0:   876: 12318 W/BpBinder        ] Large or Failed outgoing transaction of 144 bytes, interface descriptor , code 3
[ 2024-02-20T13:23:55.737        0:   876: 12318 E/JavaBinder      ] !!! FAILED BINDER TRANSACTION !!!  (parcel size = 144)
[ 2024-02-20T13:23:55.737        0:   876:  2256 W/BpBinder        ] Large or Failed outgoing transaction of 148 bytes, interface descriptor , code 3
[ 2024-02-20T13:23:55.737        0:   876:  2256 E/JavaBinder      ] !!! FAILED BINDER TRANSACTION !!!  (parcel size = 148)

</code></pre></details>

**Comment by ooil929** [comment]
一切正常，与芝麻粒无关，你该检查自己的环境

**Comment by Zhangfanyu1222** [comment]
没按照要求创建useMedia文件夹吧https://github.com/constanline/XQuickEnergy/discussions/481

**Comment by xingzaizai** [comment]
尝试以下方法正常

1.删除sdcard/Download/xqe文件夹，重启支付宝，观察sdcard/Download/xqe文件夹存在之后，再打开芝麻粒进行配置。
2.尝试在sdcard/Download目录下创建useMedia文件夹，重启支付宝

**Comment by xingzaizai** [comment]
请帮忙关闭关闭
