### ISSUE TITLE
改名了？还是合并后没改过来？

### ISSUE THREAD

**Issue by Liujishou** [constanline/XQuickEnergy#53]
![WX20230731-下午22244](https://github.com/constanline/XQuickEnergy/assets/79367462/b5824602-e84c-4b4e-a258-921230a1cf8e)

**Comment by Zhangfanyu1222** [comment]
Releases版本都还没发布呢不要着急，而且改名不影响使用

**Comment by Liujishou** [comment]
> 发布版本都还没发布呢不要着急，而且改名不影响使用

哈哈哈哈。确实不影响！
