### ISSUE TITLE
支付宝白屏，无响应

### ISSUE THREAD

**Issue by lianxia2020** [constanline/XQuickEnergy#537]
### 程序版本 / 框架版本 / 模块版本

程序版本:10.5.86.4105;框架版本:LSPosed 1.9.2(7024);模块版本:v1.2.3-beta14

### 系统版本 / Android版本

系统版本:MIUI14/Android13

### 详细描述问题发生的具体原因

在今天发现模块有新版本之后进行了更新模块，更新完模块之后强制停止zfb，然后重新启动一直卡白屏，过一会显示无响应

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

我并不知道是哪个文件提供了日志，就打包都放进去了，应该就是这几个

[anr.zip](https://github.com/constanline/XQuickEnergy/files/14915987/anr.zip)

**Comment by Nice2Boy** [comment]
我与你遇到的问题一样，这是大佬留言的，我按照要求做了后，好了。

emuoiea commented yesterday
1.安装支付宝的apk,
2.安装芝麻粒新版本,不要打开。
3.去Isp下先关闭芝麻粒
4.用管理器在Download目录下创建useMedia文件夹。
5.在Android/media文件夹下创建com.eg.android.AlipayGphone文
件夹,最后在新建的文件夹下,把原本Download文件夹下的xqe复制粘贴过来,或者直接删除,重新设置就行。
6.lsp重新勾选。
7.打开芝麻粒,重新设置等。
