### ISSUE TITLE
运动能走线路，但不能加入线路

### ISSUE THREAD

**Issue by Liujishou** [constanline/XQuickEnergy#57]
线路能走完 但不会加入，看是有相关代码 不知道是不是bug

**Comment by cwj851** [comment]
AntSportsRpcCall.java文件里的
  public static String go(String day, String rankCacheKey, int stepCount) {
                return RpcUtil.request("alipay.antsports.walk.map.go", "[{\"chInfo\":\"" + chInfo
                                + "\",\"clientOS\":\"android\",\"day\":\"" + day
                                + "\",\"features\":[\"DAILY_STEPS_RANK_V2\",\"STEP_BATTLE\",\"CLUB_HOME_CARD\",\"NEW_HOME_PAGE_STATIC\",\"CLOUD_SDK_AUTH\",\"STAY_ON_COMPLETE\",\"EXTRA_TREASURE_BOX\",\"NEW_HOME_PAGE_STATIC\",\"SUPPORT_TAB3\",\"SUPPORT_FLYRABBIT\",\"PROP\",\"PROPV2\",\"ASIAN_GAMES\"],\"needAllBox\":true,\"rankCacheKey\":\""
                                + chInfo + "\",\"timeZone\":\"" + timeZone + "\",\"useStepCount\":" + stepCount + "}]");
        }
rankCacheKey参数的chInfo改成rankCacheKey

**Comment by cwj851** [comment]
已经修复并pull等作者合并

**Comment by Liujishou** [comment]
> 修复已经并拉等作者合并

辛苦了，有增加 抢好友大战 的计划吗！！
