### ISSUE TITLE
古树新增地区：长沙

### ISSUE THREAD

**Issue by xx668888** [constanline/XQuickEnergy#60]
![QQ截图20230801222817](https://github.com/constanline/XQuickEnergy/assets/41692185/54ff7ad2-02fc-43db-81f4-731963bb9dc4)

**Comment by xx668888** [comment]
安装了1.0.11 还显示1.0.10  是不是上传错了

**Comment by ooil929** [comment]
> 



> 安装了1.0.11 还显示1.0.10 是不是上传错了

并没有上传错，只是版本号写错了而已，里面已经新增了海洋的功能了

**Comment by ooil929** [comment]
> 



> 已经支持保护了

少了长沙地区

**Comment by Liujishou** [comment]
> > 
> 
> > 已经支持保护了
> 
> 少了长沙地区

删一下配置文件 重新获取吧

**Comment by constanline** [comment]
今天会在默认选项里面添加长沙地区。其实古树功能一上线就是支持的，将cityCode.json文件放入xqe目录下即可。格式如下

**Comment by constanline** [comment]
[
{"cityCode":"320100","cityName":"南京市"},
{"cityCode":"330100","cityName":"杭州市"},
{"cityCode":"350100","cityName":"福州市"},
{"cityCode":"370100","cityName":"济南市"},
{"cityCode":"430100","cityName":"长沙市"},
{"cityCode":"440100","cityName":"广州市"}
]
