### ISSUE TITLE
我用lspatch内置之后，保活设置闹钟+activity，有时候要结束进程再重新打开才能继续收能量

### ISSUE THREAD

**Issue by laogao001** [constanline/XQuickEnergy#65]

**Comment by constanline** [comment]
如果单用芝麻粒的话，最多重新打开就能开始收能量，不需要结束进程。是否与水晶155修复版共用了？

**Comment by laogao001** [comment]
是的,和水晶155共用了

**Comment by constanline** [comment]
水晶155？还是水晶155修复版？水晶155好像没这个问题吧

**Comment by laogao001** [comment]
> 水晶155？还是水晶155修复版？水晶155好像没这个问题吧

155修复版

**Comment by constanline** [comment]
155修复版本身是有问题的，猜测会导致zfb的某些服务崩溃。所以请改用155非修复版或其他版本。
