### ISSUE TITLE
海洋功能没有工作，日志上没有运行

### ISSUE THREAD

**Issue by berebrn** [constanline/XQuickEnergy#67]
[forest.log](https://github.com/constanline/XQuickEnergy/files/12245489/forest.log)
[runtime.log](https://github.com/constanline/XQuickEnergy/files/12245492/runtime.log)

**Comment by constanline** [comment]
海洋尚未启用，如果想要测试，需要自行在“XposedHook”中调用启动方法"AntOcean.start()"。今天或明天主要功能完成后会默认启用

**Comment by berebrn** [comment]
好的，大佬辛苦啦
