### ISSUE TITLE
希望增加随机步数功能

### ISSUE THREAD

**Issue by sxj99** [constanline/XQuickEnergy#69]
规则是随机步数超过17760就会获得296g能量，希望增加一个随机步数，超过17760步，也不要太高

**Comment by berebrn** [comment]
在功能中已经有了，自己定义步数
![Screenshot_2023-08-03-10-07-22-849_pansong291 xposed quickenergy repair](https://github.com/constanline/XQuickEnergy/assets/140738041/47c05cac-ff73-4eaf-afc4-454afb033c9e)

**Comment by sxj99** [comment]
> 在功能中已经有了，自己定义步数 ![Screenshot_2023-08-03-10-07-22-849_pansong291 X安装快速能量修复](https://user-images.githubusercontent.com/140738041/257981382-47c05cac-ff73-4eaf-afc4-454afb033c9e.png)

我的意思是随机步数，不是固定的每天都一样

**Comment by berebrn** [comment]
超出17760就能获得260g能量，固定和随机不一样吗？

**Comment by Liujishou** [comment]
代码里已经加入随机数了2000，例如你填10000 其实是取10000-12000之间的数。

**Comment by constanline** [comment]
如楼上所言，步数是填入数值与其上浮2000之间随机。步数功能从上线开始一直就不允许固定步数。
