### ISSUE TITLE
大佬看一下这算不算是bug

### ISSUE THREAD

**Issue by berebrn** [constanline/XQuickEnergy#71]
![IMG_20230803_194903](https://github.com/constanline/XQuickEnergy/assets/140738041/da139320-8a89-405e-9f8e-158623701bab)
![IMG_20230803_194640](https://github.com/constanline/XQuickEnergy/assets/140738041/6610d838-4f83-4b53-9d3e-cf7e703ea3a8)
![IMG_20230803_194928](https://github.com/constanline/XQuickEnergy/assets/140738041/6d542dd5-012c-498b-8ecf-e83ce2aff974)
日志被删除会重复兑换

**Comment by constanline** [comment]
这个功能是 @cwj851 提交的代码。我查阅了代码逻辑，预期应该是每天执行一次。这位的初衷是每天获取活力值兑换限时能量双击卡，所以应该不算bug

**Comment by constanline** [comment]
删日志不受影响，你是不是把”Statistics“文件删除了

**Comment by berebrn** [comment]
> 删日志不受影响，你是不是把“Statistics”文件删除了

我没有动手删除，看日志是自动删除的，早上我还发了log

**Comment by constanline** [comment]
不是日志，是statistics，发这个看下

**Comment by berebrn** [comment]
> 不是日志，是statistics，发这个看下

![Screenshot_2023-08-04-11-02-08-793_bin mt plus](https://github.com/constanline/XQuickEnergy/assets/140738041/6a623dfc-fe93-4fdd-a155-bc5856a6139b)

**Comment by constanline** [comment]
统计里面的日期不对，不该是2023-12-18啊，是不是有什么会影响程序读取当前系统日期？如果日期变动，统计数据是会失效的。相当于到了第二天，所以会再次兑换和保护
注：其中reserveList代表保护地记录，exchangeTime代表兑换双击卡次数。

**Comment by berebrn** [comment]
会不会是曜影响，此图是曜的
![Screenshot_2023-08-04-15-48-49-698_bin mt plus](https://github.com/constanline/XQuickEnergy/assets/140738041/2a2ce352-e223-4e75-9f1d-dffb837aa16c)

**Comment by berebrn** [comment]
[farm.log](https://github.com/constanline/XQuickEnergy/files/12258435/farm.log)
这是今天运行的日志
[runtime.log](https://github.com/constanline/XQuickEnergy/files/12258438/runtime.log)

**Comment by berebrn** [comment]
昨天下午四点到11点这段日志被自动删除了

**Comment by berebrn** [comment]
![Screenshot_2023-08-04-15-58-07-250_bin mt plus](https://github.com/constanline/XQuickEnergy/assets/140738041/e0623348-be69-4f54-9d84-aa38621ae18d)
![Screenshot_2023-08-04-15-58-03-548_bin mt plus](https://github.com/constanline/XQuickEnergy/assets/140738041/85df4ecf-b430-47ec-9a4f-bcded6587015)
还会自动生成一个config文件夹，里面空的，不知道用来干嘛

**Comment by constanline** [comment]
config文件夹是之后可能会开发或者放开的功能。
日志满30m会自动删除。
现在问题不是在日志，而是在于日期不对。

**Comment by berebrn** [comment]
> config文件夹是之后可能会开发或者放开的功能。 日志满30m会自动删除。 现在问题不是在日志，而是在于日期不对。

有没有可能与手机卡顿或自动重启有问题？昨晚我已经手动更改日期，目前正常使用

**Comment by constanline** [comment]
1.0.14版输出日志会带日期，如果再出现发下forest.log看时间

**Comment by berebrn** [comment]
> 1.0.14版输出日志会带日期，如果再出现发下forest.log看时间

好的，大佬，谢谢！

**Comment by constanline** [comment]
是否还存在问题？

**Comment by berebrn** [comment]
> 是否还存在问题？

目前没有问题，如果有我再反馈。谢谢大佬！
