### ISSUE TITLE
加好友功能

### ISSUE THREAD

**Issue by 2394721412** [constanline/XQuickEnergy#76]
跪求大佬考虑一下搞个加好友的功能，有了通讯录加不了好友了，1.55修复版的那个闪退太严重了，直接没用了那个，蹲一个加好友

**Comment by Zhangfanyu1222** [comment]
好像以前有说过，有风险的功能不考虑做

**Comment by Liujishou** [comment]
希望渺茫！！

**Comment by wy41388** [comment]
没用 作者也没精力搞那么多功能， 基础大家都用得到的搞好就很厉害了
