### ISSUE TITLE
芝麻粒双开不能用[问题已解决]，类似问题可以参考

### ISSUE THREAD

**Issue by dsjun007** [constanline/XQuickEnergy#77]
芝麻粒双开之后，双开的芝麻粒和支付宝权限都开了，设置里的选项重新打勾提示保存了，再进去自然是原来的(修改不成功)，然后记录也打不开(见截图)，帮忙看看是什么问题，miui14，手机root，面具+lsp。谢谢
![Screenshot_2023-08-04-16-17-31-416_com miui securitycenter](https://github.com/constanline/XQuickEnergy/assets/139686773/92b4e385-2cee-4ebb-9993-1e9aee87972b)
![Screenshot_2023-08-04-16-17-49-702_com miui securitycenter](https://github.com/constanline/XQuickEnergy/assets/139686773/6e1491ed-1ea7-4daf-bc5b-d0f4c4ad2127)
![Screenshot_2023-08-04-18-08-58-802_pansong291 xposed quickenergy repair](https://github.com/constanline/XQuickEnergy/assets/139686773/209b4e97-ff96-4989-99c6-780efd39a210)
![Screenshot_2023-08-04-16-17-17-940_com miui securitycenter](https://github.com/constanline/XQuickEnergy/assets/139686773/1708a8e2-e43b-4037-b740-b0b1ce49fea5)

**Comment by dsjun007** [comment]
您好，来信已收到！

**Comment by lu929581942** [comment]
我的双开没问题![Screenshot_2023-08-05-00-08-48-102_com.github.android.jpg](https://github.com/constanline/XQuickEnergy/assets/118579809/fa51da49-51f9-4462-be09-473bfa8ccd5b)

**Comment by dsjun007** [comment]
翻看之前的群主解答，发现通过lsp里xspace安装的分身应用无法保存配置，通过手机应用分身直接安装的就正常了。问题已解决。

**Comment by dsjun007** [comment]
> 我的双开没问题![Screenshot_2023-08-05-00-08-48-102_com.github.android.jpg](https://user-images.githubusercontent.com/118579809/258473167-fa51da49-51f9-4462-be09-473bfa8ccd5b.jpg)

从手机应用双开生成的正常，问题解决了
