### ISSUE TITLE
建议把这个提示更改为每次打开软件的前几次才会提示

### ISSUE THREAD

**Issue by TikTokJTT** [constanline/XQuickEnergy#82]
提示几次应该能达到警示效果了，没有必要每次打开都弹出这个提示。

辛苦了！![Screenshot_2023-08-05-19-15-20-835-edit_pansong291.xposed.quickenergy.repair.png](https://github.com/constanline/XQuickEnergy/assets/83267557/9d3f8460-bb2f-446f-bcb2-365240a85ad3)

**Comment by dsjun007** [comment]
是的，每个版本第一次安装打开提示一次就行了

**Comment by alinnse** [comment]
李跳跳，Dia你值得拥有

**Comment by constanline** [comment]
目前不考虑移除
