### ISSUE TITLE
森林日志无法显示，其他日志可以正常显示

### ISSUE THREAD

**Issue by Narutojoy** [constanline/XQuickEnergy#85]
如题
Play版支付宝，1.15插件
谢谢作者！

**Comment by constanline** [comment]
发问题请描述清楚具体情况，如果闪退请带闪退日志。

**Comment by Narutojoy** [comment]
就是打开芝麻粒，和蚂蚁森林相关的日志都显示为0，但蚂蚁庄园日志，其他日志都能正常显示
![Screenshot_20230806-082909](https://github.com/constanline/XQuickEnergy/assets/25220944/66e627f1-1b4f-4ebc-8b8d-b64ba6c21959)
![Screenshot_20230806-082853](https://github.com/constanline/XQuickEnergy/assets/25220944/a47b0e63-7cec-47b9-8c97-81530d550e30)
![Screenshot_20230806-082849](https://github.com/constanline/XQuickEnergy/assets/25220944/f58a06e3-e177-4486-9d38-645d65a6bf3b)

**Comment by dsjun007** [comment]
一样，昨晚更新闪退就换回上一版本，刚更新后收取记录就都不见了，日志打开空白

**Comment by constanline** [comment]
forest.log删除或者改名试试看

**Comment by dsjun007** [comment]
这个可能跟昨晚的版本更换目录有关，闪退我就安回上一版本，行手动把原来的目录文件移到新安装目录下，记录都出来了

**Comment by Narutojoy** [comment]
> forest.log删除或者改名试试看

原文件改名后，芝麻粒重新生成了一个forest.log，森林日志还是空白

**Comment by Narutojoy** [comment]
原文件改名后，芝麻粒重新生成了一个forest.log，森林日志还是空白
![Screenshot_20230806-103246](https://github.com/constanline/XQuickEnergy/assets/25220944/fa3838d2-d4c8-4e3f-84ff-b4444907bc8d)

**Comment by Rex-Yeung** [comment]
> 原文件改名后，芝麻粒重新生成了一个forest.log，森林日志还是空白 文件管理器里的森林日志一直是0b ![Screenshot_20230806-103246](https://user-images.githubusercontent.com/25220944/258617164-fa3838d2-d4c8-4e3f-84ff-b4444907bc8d.png)

新生成的日志是空白的很正常吧？毕竟不可能把之前的日志内容补上来。

**Comment by Narutojoy** [comment]
> > 原文件改名后，芝麻粒重新生成了一个forest.log，森林日志还是空白 文件管理器里的森林日志一直是0b ![Screenshot_20230806-103246](https://user-images.githubusercontent.com/25220944/258617164-fa3838d2-d4c8-4e3f-84ff-b4444907bc8d.png)
> 
> 新生成的日志是空白的很正常吧？毕竟不可能把之前的日志内容补上来。

新生成后，又有收过好几次能量，森林日志依旧空白

**Comment by constanline** [comment]
看看runtime.log里有没有错误信息

**Comment by Narutojoy** [comment]
> 看看runtime.log里有没有错误信息

前几行是
2023-08-05 23:20:34  pansong291.xposed.quickenergy.util.Statistics, 重新格式化 statistics.json
2023-08-06 00:02:46  pansong291.xposed.quickenergy.util.Statistics, 重新格式化 statistics.json
2023-08-06 00:03:13  pansong291.xposed.quickenergy.util.Statistics, 重新格式化 statistics.json
2023-08-06 08:25:40  pansong291.xposed.quickenergy.util.Config, 重新格式化 config.json
后面就是人名列表

状态栏是有统计的，就软件里日志里没有
![Screenshot_20230808-204419](https://github.com/constanline/XQuickEnergy/assets/25220944/62ed769a-a79f-4162-941e-db401e12fa61)
![Screenshot_20230808-204423](https://github.com/constanline/XQuickEnergy/assets/25220944/aa3c74b0-6c25-4734-9791-224c577c963e)

**Comment by constanline** [comment]
runtime脱敏后发来看看

**Comment by Narutojoy** [comment]
> 只有这点吗？

我把其他的人名都删了就留了一个，类似这种
2023-08-09 12:52:35 pansong291.xposed.quickenergy.util.FriendIdMap, 2088502411093795:王|王(wss***@126.com)

**Comment by constanline** [comment]
疑似支付宝读写权限问题，所有记录到forest、farm、other的东西都会先记录到runtime和record，但是你的runtime.log里只有xqe本身记录的东西。但是download是不需要读写权限的，所以需要确认是否对支付宝做了某些限制，或者对支付宝使用了其他工具

**Comment by Narutojoy** [comment]
> 疑似支付宝读写权限问题，所有记录到forest、farm、other的东西都会先记录到runtime和record，但是你的runtime.log里只有xqe本身记录的东西。而download是不需要读写权限的，所以需要确认是否对支付宝做了某些限制，或者对支付宝使用了其他工具

大佬，我就用了个指纹支付，应该没关系吧
我这个能解决嘛，想看森林的日志😂

**Comment by Narutojoy** [comment]
![Screenshot_20230809-225257](https://github.com/constanline/XQuickEnergy/assets/25220944/4b8fe1ee-5ce5-40f3-a475-54fe650797e5)
![Screenshot_20230809-225251](https://github.com/constanline/XQuickEnergy/assets/25220944/ba47257e-2fbe-4484-8321-081008921de7)
问下大佬，日志里有显示，表面没显示，是什么原因呀

**Comment by constanline** [comment]
检查Statistics文件内容是否正常

**Comment by Narutojoy** [comment]
> 检查Statistics文件内容是否正常

![Screenshot_20230810-212104](https://github.com/constanline/XQuickEnergy/assets/25220944/274e6f7a-70b8-467f-b96c-b47e845b8f0e)

**Comment by constanline** [comment]
这个文件zfb依然没写入。

**Comment by Narutojoy** [comment]
> 这个文件zfb依然没写入。所以还是之前的问题，请确认支付宝相关配置问题

删了这文件，再重启，再开，问题解决😂
