### ISSUE TITLE
1.015打开设置闪退

### ISSUE THREAD

**Issue by shaoying189** [constanline/XQuickEnergy#86]
最新版1.015点击软件内设置闪图

**Comment by cwj851** [comment]
> 最新版1.015点击软件内设置闪图

![Screenshot_20230806_072753_com.github.android.jpg](https://github.com/constanline/XQuickEnergy/assets/53599391/8d870c65-a37d-46aa-8121-a9be31b0921a)

460行的Switch改Checkbox就不闪退了

**Comment by constanline** [comment]
已修复
