### ISSUE TITLE
请问怎么让软件一直保持运行不被踢掉？

### ISSUE THREAD

**Issue by mechanic-Q** [constanline/XQuickEnergy#88]
请问怎么让软件一直保持运行不被踢掉？
或者让程序早上七点准时启动？
我现在需要每次打开才能使用，我想让软件一直自动运行可以吗？

**Comment by TikTokJTT** [comment]
配合水晶1.55r一起使用就可以一直保持后台运行

**Comment by mechanic-Q** [comment]
> 

我不知道您说的这个是什么？能给我个链接吗

**Comment by dsjun007** [comment]
我的一直在后台运行呢。小米自带的手机管家有定时运行功能，可以试试

**Comment by TikTokJTT** [comment]
> > 
> 
> 我不知道您说的这个是什么？能给我个链接吗

https://wwjp.lanzoul.com/ijKGk10o8hvc

**Comment by Zhangfanyu1222** [comment]
用Xposed edge 设置个定时任务可以让支付宝早上七点准时启动

**Comment by TikTokJTT** [comment]
> 用Xposed edge 设置个定时任务可以让支付宝早上七点准时启动

我用Xposed edge亮屏的时候可以执行任务，锁屏的情况下就不执行任务了，什么权限都给了，搞不懂。

**Comment by Zhangfanyu1222** [comment]
> > 用Xposed edge 设置个定时任务可以让支付宝早上七点准时启动
> 
> 我用Xposed edge亮屏的时候可以执行任务，锁屏的情况下就不执行任务了，什么权限都给了，搞不懂。

那可以写个条件，if锁屏，先解锁1-3秒再执行动作，延时1-3秒锁屏

**Comment by TikTokJTT** [comment]
> > > 用Xposed edge 设置个定时任务可以让支付宝早上七点准时启动
> > 
> > 我用Xposed edge亮屏的时候可以执行任务，锁屏的情况下就不执行任务了，什么权限都给了，搞不懂。
> 
> 那可以写个条件，if锁屏，先解锁1-3秒再执行动作，延时1-3秒锁屏

现在倒是不用了，芝麻粒+水晶1.55r可以一直保持后台了。

**Comment by dsjun007** [comment]
小米手机自带的手机管家，有定时任务

**Comment by JustinTangChina** [comment]
> > > > 用Xposed edge 设置个定时任务可以让支付宝早上七点准时启动
> > > 
> > > 
> > > 我用Xposed edge亮屏的时候可以执行任务，锁屏的情况下就不执行任务了，什么权限都给了，搞不懂。
> > 
> > 
> > 那可以写个条件，if锁屏，先解锁1-3秒再执行动作，延时1-3秒锁屏
> 
> 现在倒是不用了，芝麻粒+水晶1.55r可以一直保持后台了。

开了水晶后 支付宝异常，你支付宝什么版本？我用最新版 开水晶 异常

**Comment by TikTokJTT** [comment]
> > > > > 用Xposed edge 设置个定时任务可以让支付宝早上七点准时启动
> > > > 
> > > > 
> > > > 我用Xposed edge亮屏的时候可以执行任务，锁屏的情况下就不执行任务了，什么权限都给了，搞不懂。
> > > 
> > > 
> > > 那可以写个条件，if锁屏，先解锁1-3秒再执行动作，延时1-3秒锁屏
> > 
> > 现在倒是不用了，芝麻粒+水晶1.55r可以一直保持后台了。
> 
> 开了水晶后 支付宝异常，你支付宝什么版本？我用最新版 开水晶 异常

芝麻粒+水晶1.55r+支付宝10.3.80.8800

**Comment by constanline** [comment]
#117

**Comment by constanline** [comment]
转到讨论区
