### ISSUE TITLE
希望增加个好友统计(收取能量统计)

### ISSUE THREAD

**Issue by dsjun007** [constanline/XQuickEnergy#9]
增加个好友统计(收取能量统计，每天和历史收取量)，这样可以筛选好友，谢谢。
![IMG_20230716_231826](https://github.com/constanline/XQuickEnergy/assets/139686773/7a91afa3-5415-45f5-a690-718cab89e424)

**Comment by lee-ley** [comment]
非常棒的项目，相信和鼓励作者一定能完善它，谢谢！

**Comment by dsjun007** [comment]
您好，来信已收到！

**Comment by shaoying189** [comment]
这个比较不错，支持

**Comment by constanline** [comment]
已添加

**Comment by dsjun007** [comment]
大佬威武，现在的界面超级棒，功能也越来越多了。辛苦了
