### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by chicmr** [constanline/XQuickEnergy#90]
蚂蚁庄园饲料满1500g了之后还会自动领取吗？超上限领了就会浪费

**Comment by Liujishou** [comment]
不会吧！看代码里是 限制的

**Comment by Zhangfanyu1222** [comment]
饲料满1800是不会自动领的，只要领取会超出就不会再继续领

**Comment by constanline** [comment]
程序里有限制，但不全面。庄园本身也有限制。另外好像是1800g而不是1500g
