### ISSUE TITLE
日志只有第一行正常输出，第二行开始乱码

### ISSUE THREAD

**Issue by j4Uq** [constanline/XQuickEnergy#92]
系统更新到Android13后开始出现的，不管是用水晶还是芝麻粒都有这个问题
删除log文件重新生成日志还是会出现
但是其他app都没这个问题，只有用过的这2个支付宝辅助有这个问题
![Screenshot_20230807-162350](https://github.com/constanline/XQuickEnergy/assets/6436073/e6bb6af4-b882-4ef1-8c3c-b1b20cbdc9f8)

**Comment by Rex-Yeung** [comment]
水晶也有这个问题，那你该思考是不是你自己的问题了。

**Comment by Rex-Yeung** [comment]
> > 水晶也有这个问题，那你该思考是不是你自己的问题了。
> 
> 我更新Android13后，换过好几个rom，不管是miui，还是类原生，一直存在这个问题 刚刚还把所有magisk和lsp关的只剩lsposed和芝麻粒，还是这样 想不出还有啥可能了

我也是Android13，完全没有这个问题。

**Comment by cls-292** [comment]
Try uninstalling and reinstalling

**Comment by constanline** [comment]
用其他文本编辑器打开看看

**Comment by AIerlIz** [comment]
![Screenshot_20230808-110851_设置.png](https://github.com/constanline/XQuickEnergy/assets/40273202/9c8dce15-8e89-4b48-a8a4-454e2ed469e3)

![Screenshot_20230808-110940_XQ_Crystal.png](https://github.com/constanline/XQuickEnergy/assets/40273202/8ef9670c-2945-43f2-8624-3feddd63bf93)

**Comment by zhangguanzhang** [comment]
不支持emoji表情啥的吧，把log文件导出来后在pc的vscode上打开看看

**Comment by constanline** [comment]
看起来好像是不支持追加输出，是被什么限制了吧。
