### ISSUE TITLE
【高风险】包含病毒：a.gray.GmPluginTools

### ISSUE THREAD

**Issue by roger1419** [constanline/XQuickEnergy#95]
小米手机扫描出，【高风险】包含病毒：a.gray.GmPluginTools，这个是不是误报呀

**Comment by constanline** [comment]
拿这个问题问我就很奇怪，这个是不是误报不应该问我啊，我肯定这没有任何病毒和木马成分，但是我是开发者啊。。。
建议找熟识的人鉴别源码，确认源码是否安全，然后拉取源码自行编译学习，不要下载其他人编译的程序。

**Comment by roger1419** [comment]
点赞
