### ISSUE TITLE
1.0.17点开好友统计列表后，列表显示异常

### ISSUE THREAD

**Issue by LazyImmortal** [constanline/XQuickEnergy#98]
1.首页没点开好友统计时，设置里所有的列表都能正常点击打开并显示。[图一]
2.在首页点开了好友统计之后，设置里所有的列表点击后都需要返回首页才能显示。[图二]
![Screenshot_2023-08-08-22-02-43-987_pansong291 xposed quickenergy repair](https://github.com/constanline/XQuickEnergy/assets/44522979/5397a4e7-8b48-4bb3-b8a1-2d0228b2628e)
![Screenshot_2023-08-08-22-03-02-627_pansong291 xposed quickenergy repair](https://github.com/constanline/XQuickEnergy/assets/44522979/3323d09f-5398-4e16-b412-6f7e1e85942f)

**Comment by constanline** [comment]
已修复
